import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Agriculture',
  slug: 'agriculture-precision',
  description: 'Transform farming with precision agriculture, IoT sensors, and satellite imagery analysis.',
  orderIndex: 37,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'precision_ag_basics', name: 'Precision Agriculture Basics', description: 'Understand GPS-guided farming, variable rate technology, and data-driven crop management.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Data-Driven Farming', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Precision agriculture uses GPS and sensors to optimize field-level management.', 'Variable rate technology applies inputs at site-specific rates for efficiency.', 'Yield mapping measures crop production across fields for analysis.'] }], quiz: [q('What is variable rate technology?', ['Fixed application rates', 'Applying inputs at site-specific rates based on field conditions', 'Manual farming only', 'Chemical mixing'], 1, 'VRT adjusts fertilizer, seed, and chemical application based on soil and crop conditions at each location.')] },
  { slug: 'farm_iot', name: 'Farm IoT', description: 'Deploy sensors for soil moisture, weather monitoring, and livestock tracking across operations.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Connected Farm Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Soil sensors measure moisture, temperature, and nutrient levels in real-time.', 'Weather stations provide microclimate data for field-specific decisions.', 'GPS trackers monitor livestock location and health metrics.'] }], quiz: [q('What data do soil sensors provide?', ['Only temperature', 'Moisture, temperature, and nutrient levels', 'Weather only', 'Crop yield'], 1, 'Soil sensors measure multiple parameters to guide irrigation and fertilization decisions.')] },
  { slug: 'satellite_imagery', name: 'Satellite Imagery', description: 'Analyze crop health, detect stress, and monitor fields with satellite and drone imagery.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Remote Sensing for Agriculture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['NDVI analysis identifies crop stress from satellite and drone imagery.', 'Multispectral imaging detects issues invisible to the human eye.', 'Time-series analysis tracks crop development throughout growing seasons.'] }], quiz: [q('What does NDVI measure?', ['Soil quality', 'Crop health from vegetation index analysis', 'Water levels', 'Pest populations'], 1, 'NDVI uses spectral analysis to assess plant health and identify areas of stress or disease.')] },
  { slug: 'crop_analytics', name: 'Crop Analytics', description: 'Predict yields, optimize irrigation, and manage pests with machine learning models.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Agricultural Data Science', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Yield prediction models forecast harvest volumes for planning and marketing.', 'Irrigation optimization uses soil and weather data to schedule water application.', 'Pest detection identifies insect damage from images and sensor data.'] }], quiz: [q('How does predictive analytics help farming?', ['Replaces manual labor', 'Forecasts yields and optimizes resource application', 'Eliminates weather impact', 'Guarantees profits'], 1, 'Analytics provide data-driven insights for better decision-making in planting, irrigation, and harvesting.')] },
  { slug: 'agriculture_ai', name: 'Agriculture AI', description: 'Apply computer vision and deep learning to crop monitoring, weed detection, and harvest automation.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Agriculture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Computer vision identifies weeds for precision herbicide application.', 'Deep learning models classify plant species and disease stages.', 'Autonomous tractors use AI for navigation and crop management tasks.'] }], quiz: [q('How does computer vision help weed control?', ['Counts weeds only', 'Identifies weed species for targeted herbicide application', 'Removes weeds manually', 'Prevents weed growth'], 1, 'Computer vision distinguishes weeds from crops, enabling precise herbicide application and reducing chemical use.')] },
  { slug: 'agriculture_enterprise', name: 'Agriculture Enterprise', description: 'Integrate farm management with supply chain, market data, and compliance systems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Agricultural Business Systems', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Farm management software coordinates planting, harvesting, and inventory.', 'Supply chain integration tracks produce from field to consumer.', 'Compliance systems manage organic certification and food safety requirements.'] }], quiz: [q('What is farm management software?', ['Accounting only', 'Coordinates all farm operations from planning to harvest', 'Weather app', 'GPS only'], 1, 'Farm management platforms integrate planting, operations, inventory, and financial management.')] },
];
