import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Application Integration',
  slug: 'application-integration',
  description: 'Connect distributed systems and microservices with messaging, queuing, and event-driven patterns.',
  orderIndex: 18,
  theme: 'CITADEL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'sqs_basics', name: 'Amazon SQS Basics', description: 'Decouple application components with fully managed message queuing for reliable data delivery.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Message Queuing Fundamentals', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['SQS provides reliable, scalable message queuing between application components.', 'Standard queues offer best-effort ordering with at-least-once delivery.', 'FIFO queues guarantee message ordering and exactly-once processing.'] }], quiz: [q('Which SQS queue type guarantees message ordering?', ['Standard', 'FIFO', 'Dead-letter', 'Delayed'], 1, 'FIFO queues maintain message order and prevent duplicates for precise processing sequences.')] },
  { slug: 'sqs_advanced', name: 'SQS Advanced Features', description: 'Configure dead-letter queues, message retention, and long polling for production workloads.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Production Queue Configuration', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Dead-letter queues capture messages that fail processing after configurable retry attempts.', 'Long polling reduces empty responses by waiting for messages to arrive.', 'Message retention periods can be set from 1 minute to 14 days.'] }], quiz: [q('What is the purpose of a dead-letter queue?', ['Store messages permanently', 'Capture messages that fail processing after retries', 'Queue messages for deletion', 'Archive old messages'], 1, 'Dead-letter queues isolate problematic messages for debugging without blocking the main queue.')] },
  { slug: 'sns_fundamentals', name: 'Amazon SNS Fundamentals', description: 'Publish messages to multiple subscribers with fully managed pub/sub messaging service.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Publish-Subscribe Messaging', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['SNS delivers messages to multiple subscribers simultaneously using pub/sub pattern.', 'Subscribers can receive messages via HTTP/S, email, SMS, SQS, or Lambda.', 'Topic policies control who can publish and subscribe to topics.'] }], quiz: [q('What is an SNS topic?', ['A message queue', 'A communication channel for publishing messages to subscribers', 'An IAM role', 'A CloudWatch alarm'], 1, 'Topics are communication channels that route messages from publishers to all subscribed endpoints.')] },
  { slug: 'eventbridge', name: 'Amazon EventBridge', description: 'Build event-driven architectures with serverless event bus for application integration.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Serverless Event Bus', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['EventBridge routes events from AWS services, SaaS applications, and custom sources.', 'Rules filter and route events to targets like Lambda, SQS, or Step Functions.', 'Schema registry automatically discovers and catalogs event schemas.'] }], quiz: [q('What does EventBridge use to route events to targets?', ['IAM roles', 'Rules', 'VPCs', 'Security groups'], 1, 'Rules define patterns that match incoming events and route them to configured targets.')] },
  { slug: 'step_functions', name: 'AWS Step Functions', description: 'Orchestrate serverless workflows with visual state machines for complex business processes.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Workflow Orchestration', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Step Functions coordinate multiple AWS services into serverless workflows.', 'Standard workflows handle long-running, auditable workloads up to one year.', 'Express workflows handle high-volume, short-duration tasks with sub-second billing.'] }], quiz: [q('What is the maximum duration for a Standard Step Functions workflow?', ['5 minutes', '1 hour', '1 year', 'Unlimited'], 2, 'Standard workflows can run for up to one year, making them suitable for long-running processes.')] },
  { slug: 'saga_pattern', name: 'Saga Pattern', description: 'Implement distributed transactions with compensating actions for microservice architectures.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Distributed Transaction Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['The saga pattern coordinates multiple services with compensating transactions for rollbacks.', 'Choreography-based sagas use events to trigger next steps without central coordination.', 'Orchestration-based sagas use a central coordinator to manage the workflow sequence.'] }], quiz: [q('What is a compensating transaction in the saga pattern?', ['A database commit', 'An action that reverses a previous step on failure', 'A backup transaction', 'A retry mechanism'], 1, 'Compensating transactions undo previous work when a step fails, maintaining data consistency across services.')] },
];
