import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Automotive',
  slug: 'automotive-connected',
  description: 'Build connected vehicle platforms with telematics, autonomous driving, and EV charging solutions.',
  orderIndex: 29,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'connected_vehicle', name: 'Connected Vehicle Basics', description: 'Understand telematics, V2X communication, and connected car data platforms.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Connected Car Technology', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Telematics systems collect vehicle data including location, speed, and diagnostics.', 'V2X communication enables vehicles to communicate with infrastructure and other cars.', 'Connected car platforms process millions of events from fleet vehicles daily.'] }], quiz: [q('What data do telematics systems collect?', ['Only GPS location', 'Vehicle diagnostics, location, speed, and driver behavior', 'Only fuel level', 'Passenger information'], 1, 'Telematics captures comprehensive vehicle and driver data for fleet management and safety.')] },
  { slug: 'fleet_management', name: 'Fleet Management', description: 'Track and optimize vehicle fleets with real-time GPS, routing, and maintenance scheduling.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Fleet Operations Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GPS tracking provides real-time vehicle location and route optimization.', 'Predictive maintenance schedules repairs based on actual vehicle usage patterns.', 'Driver behavior scoring identifies risky driving for safety improvement programs.'] }], quiz: [q('How does fleet management improve efficiency?', ['Increases speed', 'Optimizes routes and reduces fuel consumption', 'Eliminates maintenance', 'Reduces vehicle count'], 1, 'Route optimization and predictive maintenance reduce costs while improving vehicle utilization.')] },
  { slug: 'autonomous_driving', name: 'Autonomous Driving Data', description: 'Process petabytes of sensor data from cameras, LiDAR, and radar for self-driving systems.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Self-Driving Data Pipeline', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Autonomous vehicles generate terabytes of sensor data per day from multiple sources.', 'Data labeling and annotation create training datasets for ML perception models.', 'Simulation environments test driving algorithms in virtual scenarios safely.'] }], quiz: [q('How much data can an autonomous vehicle generate per day?', ['Megabytes', 'Gigabytes', 'Terabytes', 'Petabytes'], 2, 'Self-driving cars with multiple sensors generate terabytes of raw data requiring cloud-scale processing.')] },
  { slug: 'ev_charging', name: 'EV Charging Infrastructure', description: 'Deploy smart charging networks with load management and grid integration.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Electric Vehicle Charging', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Smart charging optimizes power distribution based on grid capacity and demand.', 'OCPP protocols enable communication between chargers and management systems.', 'Vehicle-to-grid integration allows EVs to supply power back to the electrical grid.'] }], quiz: [q('What is vehicle-to-grid (V2G) technology?', ['Charging vehicles faster', 'Allowing EVs to supply power back to the electrical grid', 'Wireless charging', 'Battery swapping'], 1, 'V2G enables EVs to act as distributed energy storage, supporting grid stability during peak demand.')] },
  { slug: 'automotive_ai', name: 'Automotive AI', description: 'Apply machine learning to driver assistance, predictive maintenance, and in-vehicle experiences.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI in Automotive', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['ADAS systems use computer vision for lane detection and collision avoidance.', 'Natural language processing enables voice-controlled in-vehicle assistants.', 'Predictive analytics anticipate driver needs based on historical patterns.'] }], quiz: [q('What does ADAS stand for?', ['Advanced Driver Assistance Systems', 'Automated Data Analytics Service', 'Automatic Deployment Architecture', 'Adaptive Driving Algorithm Standard'], 0, 'ADAS uses sensors and AI to assist drivers with safety and automation features.')] },
  { slug: 'automotive_enterprise', name: 'Automotive Enterprise', description: 'Integrate connected vehicle data with dealership, warranty, and customer experience platforms.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Digital Automotive Ecosystem', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Over-the-air updates deliver new features and security patches to vehicles remotely.', 'Dealer management systems integrate vehicle telemetry for proactive service outreach.', 'Customer apps provide remote vehicle access, diagnostics, and concierge services.'] }], quiz: [q('What is the benefit of over-the-air vehicle updates?', ['Faster acceleration', 'Remote delivery of software updates without dealer visits', 'Better fuel economy', 'Improved外观'], 1, 'OTA updates deliver new features and fixes remotely, improving vehicles without service appointments.')] },
];
