import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'AWS Managed Services',
  slug: 'aws-managed-services',
  description: 'Leverage AWS Managed Services and support programs for operational excellence and cost optimization.',
  orderIndex: 45,
  theme: 'CITADEL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'support_plans', name: 'AWS Support Plans', description: 'Understand Basic, Developer, Business, and Enterprise support tiers and benefits.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'AWS Support Tiers', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Basic support provides documentation and community forums.', 'Developer support adds email access to cloud support associates.', 'Business support provides 24/7 phone and chat access to cloud support engineers.'] }], quiz: [q('Which support plan provides 24/7 phone access?', ['Basic', 'Developer', 'Business', 'None'], 2, 'Business and Enterprise support plans include 24/7 access to cloud support engineers.')] },
  { slug: 'enterprise_support', name: 'Enterprise Support', description: 'Access Technical Account Managers, Concierge Support, and Infrastructure Event Management.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Enterprise Support Benefits', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Technical Account Managers provide proactive guidance and advocacy.', 'Concierge Support teams handle account and billing inquiries.', 'Infrastructure Event Management assists with planned events and launches.'] }], quiz: [q('What is a Technical Account Manager?', ['Sales representative', 'Proactive technical advisor for enterprise customers', 'Support agent', 'Developer'], 1, 'TAMs provide proactive guidance, best practices, and advocacy for enterprise customers.')] },
  { slug: 'trusted_advisor', name: 'AWS Trusted Advisor', description: 'Optimize costs, improve security, and enhance performance with automated recommendations.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Automated Best Practices', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Cost optimization checks identify unused or underutilized resources.', 'Security checks detect common security misconfigurations.', 'Performance checks recommend improvements for better application performance.'] }], quiz: [q('What does Trusted Advisor check for?', ['Code quality only', 'Cost, security, performance, and fault tolerance best practices', 'Network speed', 'Hardware status'], 1, 'Trusted Advisor evaluates environments against AWS best practices across multiple categories.')] },
  { slug: 'cost_explorer', name: 'AWS Cost Explorer', description: 'Visualize, analyze, and manage AWS costs with forecasting and budgeting tools.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Cost Management Tools', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Cost Explorer visualizes spending patterns by service, account, and tag.', 'Forecasting predicts future costs based on historical usage patterns.', 'Budgets set spending thresholds with alerts for cost control.'] }], quiz: [q('What is the primary purpose of Cost Explorer?', ['Increase spending', 'Visualize and analyze AWS costs for optimization', 'Manage user access', 'Deploy applications'], 1, 'Cost Explorer helps understand spending patterns and identify cost optimization opportunities.')] },
  { slug: 'ams_overview', name: 'AWS Managed Services', description: 'Outsource cloud operations to AWS for infrastructure management and operational support.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AWS-Managed Operations', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AMS provides ongoing management of AWS infrastructure and applications.', 'Operational runbooks automate common infrastructure management tasks.', 'Proactive monitoring detects and resolves issues before they impact users.'] }], quiz: [q('What does AWS Managed Services provide?', ['Development tools only', 'Infrastructure management and operational support by AWS', 'Hardware only', 'Training only'], 1, 'AMS handles day-to-day infrastructure operations including monitoring, patching, and incident response.')] },
  { slug: 'support_enterprise', name: 'Enterprise Support Excellence', description: 'Maximize support value with TAM engagement, operational reviews, and optimization planning.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Strategic Support Engagement', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Quarterly business reviews align AWS usage with business objectives.', 'Operational reviews identify improvement opportunities and best practices.', 'Well-Architected reviews provide deep architectural assessments.'] }], quiz: [q('What is a quarterly business review?', ['Weekly meeting', 'Strategic alignment meeting between AWS and customer leadership', 'Technical support call', 'Training session'], 1, 'QBRs review AWS usage, costs, and strategic alignment with business objectives.')] },
];
