import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Blockchain',
  slug: 'blockchain-managed',
  description: 'Build decentralized applications and managed blockchain networks with Amazon Managed Blockchain.',
  orderIndex: 22,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'blockchain_basics', name: 'Blockchain Basics', description: 'Understand distributed ledger technology, consensus mechanisms, and smart contracts.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Distributed Ledger Technology', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Blockchain maintains a decentralized, immutable record of transactions across multiple nodes.', 'Consensus mechanisms like Proof of Work and Proof of Stake validate transactions.', 'Smart contracts execute automatically when predefined conditions are met.'] }], quiz: [q('What makes blockchain transactions immutable?', ['Password protection', 'Cryptographic linking of blocks in a chain', 'Cloud storage', 'Database replication'], 1, 'Each block contains a hash of the previous block, creating a tamper-evident chain of records.')] },
  { slug: 'managed_blockchain', name: 'Amazon Managed Blockchain', description: 'Create and manage scalable blockchain networks with Hyperledger Fabric or Ethereum.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Managed Blockchain Networks', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Managed Blockchain provisions Hyperledger Fabric or Ethereum networks automatically.', 'Memberships control network access and permissions for participating organizations.', 'Nodes run blockchain frameworks with managed infrastructure and monitoring.'] }], quiz: [q('Which blockchain frameworks does Managed Blockchain support?', ['Only Bitcoin', 'Hyperledger Fabric and Ethereum', 'Only Ethereum', 'Ripple and Stellar'], 1, 'Managed Blockchain supports Hyperledger Fabric for private networks and Ethereum for public networks.')] },
  { slug: 'qldb', name: 'Amazon QLDB', description: 'Build applications requiring a transparent, immutable, and cryptographically verifiable ledger.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Quantum Ledger Database', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['QLDB provides a fully managed ledger database with an immutable transaction log.', 'Documents are stored in a document data model with SQL-like query capabilities.', 'SHA-256 hashing creates a verifiable chain of data changes over time.'] }], quiz: [q('How does QLDB differ from traditional databases?', ['Faster queries', 'Immutable and cryptographically verifiable transaction history', 'Lower cost', 'Higher availability'], 1, 'QLDB maintains a complete, verifiable history of all data changes that cannot be altered.')] },
  { slug: 'smart_contracts', name: 'Smart Contracts', description: 'Develop and deploy self-executing business logic on blockchain networks.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Automated Business Logic', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Smart contracts are code deployed on blockchain that executes automatically.', 'Chaincode in Hyperledger Fabric implements business logic for transactions.', 'Testing smart contracts requires simulated blockchain environments.'] }], quiz: [q('What language is Hyperledger Fabric chaincode typically written in?', ['Python only', 'Go, Java, or JavaScript', 'Solidity only', 'C++ only'], 1, 'Hyperledger Fabric supports chaincode in Go, Java, and JavaScript for flexible development.')] },
  { slug: 'blockchain_security', name: 'Blockchain Security', description: 'Implement cryptographic security, access control, and audit trails for blockchain applications.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Distributed Security Model', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Cryptographic signatures authenticate transaction creators and prevent forgery.', 'Channel isolation in Hyperledger Fabric separates confidential transactions.', 'Endorsement policies require multiple organizations to validate transactions.'] }], quiz: [q('What do endorsement policies control?', ['User passwords', 'Which organizations must approve a transaction before it is committed', 'Network speed', 'Data storage location'], 1, 'Endorsement policies define how many and which organizations must sign a transaction for validity.')] },
  { slug: 'blockchain_enterprise', name: 'Enterprise Blockchain', description: 'Design production blockchain networks with governance, scalability, and interoperability patterns.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Production Blockchain Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Network governance defines rules for adding members and upgrading chaincode.', 'Off-chain storage handles large data with on-chain hashes for verification.', 'Interoperability patterns connect multiple blockchain networks for cross-organization workflows.'] }], quiz: [q('Why use off-chain storage with blockchain?', ['Reduce costs', 'Store large data off-chain with hashes on-chain for verification', 'Increase speed', 'Simplify development'], 1, 'Off-chain storage keeps large files accessible while maintaining integrity through on-chain cryptographic hashes.')] },
];
