import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'CI/CD Pipelines',
  slug: 'cicd-pipelines',
  description: 'Automate build, test, and deployment workflows with continuous integration and delivery on AWS.',
  orderIndex: 12,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'codecommit', name: 'AWS CodeCommit', description: 'Host private Git repositories with secure access control and integration with other AWS services.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Source Control with CodeCommit', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CodeCommit is a fully managed source control service that hosts Git repositories.', 'It integrates with CodeBuild, CodeDeploy, and CodePipeline for end-to-end automation.', 'Repositories support pull requests, branch permissions, and triggers for notifications.'] }], quiz: [q('What is the primary purpose of AWS CodeCommit?', ['Run CI/CD pipelines', 'Host private Git repositories', 'Deploy applications to EC2', 'Monitor application logs'], 1, 'CodeCommit is a managed Git service for hosting private repositories with AWS integration.')] },
  { slug: 'codebuild', name: 'AWS CodeBuild', description: 'Compile source code, run tests, and produce build artifacts in a fully managed build service.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Managed Build Service', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CodeBuild compiles source code, runs tests, and creates deployable packages.', 'Build specifications (buildspec.yml) define build steps, environment, and artifacts.', 'CodeBuild scales automatically and charges only for build time used.'] }], quiz: [q('What file defines the build steps in CodeBuild?', ['Dockerfile', 'buildspec.yml', 'Makefile', 'pipeline.yaml'], 1, 'The buildspec.yml file defines build phases, environment variables, and artifact configurations for CodeBuild.')] },
  { slug: 'codedeploy', name: 'AWS CodeDeploy', description: 'Automate code deployments to EC2, Lambda, and on-premises servers with zero-downtime strategies.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Automated Deployment', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CodeDeploy automates deployments to EC2 instances, Lambda functions, and on-premises servers.', 'Deployment configurations include AllAtOnce, Linear, and Canary for controlled rollouts.', 'It integrates with auto-scaling groups and Elastic Load Balancing for zero-downtime deployments.'] }], quiz: [q('Which CodeDeploy strategy deploys to a subset of instances, waits, then continues?', ['AllAtOnce', 'Canary', 'OneAtATime', 'Rolling'], 1, 'Canary deployments route a percentage of traffic to the new version before full deployment, enabling safe rollbacks.')] },
  { slug: 'codepipeline', name: 'AWS CodePipeline', description: 'Orchestrate multi-stage CI/CD workflows from source to production with visual pipeline management.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Pipeline Orchestration', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CodePipeline orchestrates the steps to release software through build, test, and deploy stages.', 'Each stage can have multiple actions running in parallel or sequentially.', 'Pipelines can be triggered by source changes, schedules, or manual approval actions.'] }], quiz: [q('What is a stage in CodePipeline?', ['A deployment target environment', 'A logical grouping of actions within a pipeline', 'A type of build artifact', 'An IAM permission boundary'], 1, 'Stages are logical groupings of actions that perform a specific part of the release process.')] },
  { slug: 'cicd_advanced', name: 'Advanced CI/CD Patterns', description: 'Implement blue/green deployments, pipeline security, and multi-account promotion strategies.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Advanced Pipeline Patterns', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Blue/green deployments switch traffic between two identical environments for safe releases.', 'Pipeline roles with least-privilege IAM policies prevent unauthorized deployment access.', 'Multi-account promotion moves artifacts from dev to staging to production with approval gates.'] }], quiz: [q('What is the benefit of blue/green deployments?', ['Faster build times', 'Instant rollback by switching traffic back to the original environment', 'Reduced infrastructure costs', 'Automatic code review'], 1, 'Blue/green deployments allow instant rollback by switching traffic back to the previous environment if issues are detected.')] },
  { slug: 'devops_automation', name: 'DevOps Automation', description: 'Automate infrastructure provisioning, configuration management, and operational tasks with AWS tools.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'End-to-End Automation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS Systems Manager automates operational tasks across EC2 instances and on-premises servers.', 'Parameter Store provides hierarchical configuration data and secrets management.', 'Automation runbooks execute common operational procedures without manual intervention.'] }], quiz: [q('Which AWS service provides centralized operational automation across your fleet?', ['CloudWatch', 'Systems Manager', 'CodeDeploy', 'Lambda'], 1, 'Systems Manager provides automation runbooks, patch management, and session management for fleet operations.')] },
];
