import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Construction Technology',
  slug: 'construction-tech',
  description: 'Modernize construction with BIM, IoT sensors, and project management platforms.',
  orderIndex: 42,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'bim_basics', name: 'BIM Fundamentals', description: 'Understand Building Information Modeling for collaborative construction design and planning.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Digital Construction Modeling', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['BIM creates intelligent 3D models with construction data and metadata.', 'Clash detection identifies design conflicts before construction begins.', '4D BIM adds scheduling to models for construction sequencing visualization.'] }], quiz: [q('What is clash detection in BIM?', ['Finding software bugs', 'Identifying design conflicts between building systems', 'Quality inspection', 'Safety monitoring'], 1, 'Clash detection automatically identifies where building components overlap or conflict in designs.')] },
  { slug: 'construction_iot', name: 'Construction IoT', description: 'Deploy sensors for equipment tracking, safety monitoring, and progress documentation.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Connected Construction Sites', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GPS trackers monitor equipment location and utilization across job sites.', 'Wearable sensors detect safety hazards and worker fatigue.', 'Progress cameras document construction milestones automatically.'] }], quiz: [q('How does IoT improve construction safety?', ['Faster internet', 'Detects hazards and monitors worker conditions in real-time', 'Reduces materials', 'Speeds up construction'], 1, 'IoT sensors identify safety risks and alert workers and managers to prevent accidents.')] },
  { slug: 'project_management', name: 'Construction Project Management', description: 'Coordinate schedules, resources, and budgets with cloud-based project management tools.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Digital Project Coordination', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Gantt charts visualize construction schedules and task dependencies.', 'Resource leveling optimizes equipment and crew allocation.', 'Change order management tracks scope modifications and cost impacts.'] }], quiz: [q('What is resource leveling?', ['Removing resources', 'Optimizing allocation of equipment and crews across tasks', 'Reducing budget', 'Hiring more workers'], 1, 'Resource leveling balances resource demand with available supply to prevent overallocation.')] },
  { slug: 'safety_compliance', name: 'Construction Safety', description: 'Manage OSHA compliance, safety training, and incident reporting with digital systems.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Digital Safety Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Digital safety checklists ensure daily inspections are completed.', 'Incident reporting apps capture and track safety events in real-time.', 'Training management tracks worker certifications and safety education.'] }], quiz: [q('What is the benefit of digital safety checklists?', ['Paper savings only', 'Ensures consistent completion and provides audit trails', 'Faster completion', 'Better visibility'], 1, 'Digital checklists ensure inspections are completed consistently and create records for compliance.')] },
  { slug: 'construction_ai', name: 'Construction AI', description: 'Apply machine learning to progress tracking, safety prediction, and material optimization.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI in Construction', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Computer vision analyzes site photos to track construction progress.', 'Predictive models identify safety risks before incidents occur.', 'Material optimization reduces waste through better demand forecasting.'] }], quiz: [q('How does AI improve construction safety?', ['Replaces workers', 'Predicts and prevents safety incidents proactively', 'Faster construction', 'Lower costs'], 1, 'AI analyzes patterns to identify potential safety hazards before they cause incidents.')] },
  { slug: 'construction_enterprise', name: 'Construction Enterprise', description: 'Scale construction operations with multi-project management, supply chain, and fleet coordination.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise Construction Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Multi-project dashboards provide visibility across construction portfolios.', 'Supply chain coordination manages material deliveries and inventory.', 'Equipment fleet management optimizes utilization across job sites.'] }], quiz: [q('What is multi-project management?', ['Single project focus', 'Coordinating multiple construction projects from one platform', 'Only financial management', 'Equipment tracking only'], 1, 'Multi-project platforms provide centralized oversight and resource coordination across construction portfolios.')] },
];
