import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Data Warehousing',
  slug: 'data-warehousing',
  description: 'Build and optimize data warehouses with Amazon Redshift for analytics and business intelligence.',
  orderIndex: 15,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'redshift_basics', name: 'Redshift Basics', description: 'Launch and query a petabyte-scale data warehouse with Amazon Redshift.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Columnar Data Warehouse', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Redshift is a fast, fully managed data warehouse for analytics queries.', 'Columnar storage reduces I/O by reading only the columns needed for a query.', 'Redshift Spectrum allows querying data directly in S3 without loading it into Redshift.'] }], quiz: [q('What storage architecture does Redshift use for fast analytics?', ['Row-based storage', 'Columnar storage', 'Object storage', 'Block storage'], 1, 'Columnar storage organizes data by columns rather than rows, dramatically improving query performance for analytics.')] },
  { slug: 'redshift_query', name: 'Redshift Query Optimization', description: 'Optimize query performance with distribution styles, sort keys, and materialized views.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Query Performance Tuning', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Distribution styles (KEY, EVEN, ALL, AUTO) control how data is distributed across nodes.', 'Sort keys define the physical order of data for fast range-based filtering.', 'Materialized views pre-compute expensive queries for instant results.'] }], quiz: [q('Which distribution style copies the table to every node for small dimension tables?', ['KEY', 'EVEN', 'ALL', 'AUTO'], 2, 'ALL distribution copies the table to every node, eliminating network traffic for joins with small tables.')] },
  { slug: 'redshift_advanced', name: 'Redshift Advanced', description: 'Configure concurrency scaling, workload management, and cross-cluster data sharing.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Enterprise Features', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Concurrency scaling adds temporary clusters automatically during peak query loads.', 'Workload Management (WLM) queues allocate memory and concurrency across user groups.', 'Data sharing allows read-only access to Redshift clusters across AWS accounts.'] }], quiz: [q('What does Redshift concurrency scaling do?', ['Increases node storage', 'Adds temporary clusters to handle peak query loads', 'Reduces query complexity', 'Archives old data'], 1, 'Concurrency scaling automatically provisions additional read-only clusters during high-demand periods.')] },
  { slug: 'etl_pipeline', name: 'ETL with Glue', description: 'Build extract-transform-load pipelines with AWS Glue for data preparation and cataloging.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Serverless ETL', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS Glue is a serverless ETL service that discovers and prepares data for analytics.', 'The Glue Data Catalog stores metadata tables and partitions across data stores.', 'Glue Studio provides a visual editor for building ETL jobs without code.'] }], quiz: [q('What is the primary purpose of the AWS Glue Data Catalog?', ['Run SQL queries', 'Store metadata tables and partitions for data discovery', 'Deploy Lambda functions', 'Manage VPC configurations'], 1, 'The Data Catalog acts as a central metadata repository, making data discoverable and queryable across AWS analytics services.')] },
  { slug: 'redshift_serverless', name: 'Redshift Serverless', description: 'Run analytics workloads without managing clusters using Redshift Serverless.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Serverless Analytics', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Redshift Serverless scales compute capacity based on query complexity and data volume.', 'Pay only for the compute seconds used — no idle cluster costs.', 'Base capacity (RPUs) configures the minimum and maximum compute available.'] }], quiz: [q('How does Redshift Serverless handle scaling?', ['Fixed cluster size', 'Automatically scales compute based on query demand', 'Manual resizing required', 'Only scales read replicas'], 1, 'Redshift Serverless automatically adjusts compute capacity up and down based on current query workload.')] },
  { slug: 'data_modeling', name: 'Data Warehouse Modeling', description: 'Design star schemas, snowflake schemas, and slowly changing dimensions for analytical workloads.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Dimensional Modeling', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Star schema connects fact tables to dimension tables for intuitive querying.', 'Snowflake schema normalizes dimension tables to reduce data redundancy.', 'Slowly Changing Dimensions (SCD) track historical changes to dimension attributes over time.'] }], quiz: [q('What is a fact table in a star schema?', ['Contains dimension attributes', 'Stores measurable business metrics like revenue and quantity', 'Stores user authentication data', 'Contains ETL job logs'], 1, 'Fact tables store quantitative measurements (facts) of business processes, linked to dimension tables for context.')] },
];
