import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Desktop & App Streaming',
  slug: 'desktop-app-streaming',
  description: 'Deliver virtual desktops and applications to any device with WorkSpaces and AppStream 2.0.',
  orderIndex: 21,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'workspaces_basics', name: 'Amazon WorkSpaces Basics', description: 'Provision cloud-based virtual desktops for secure, managed end-user computing.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Virtual Desktop Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['WorkSpaces provides persistent cloud desktops accessible from any device.', 'Bundles define the operating system, applications, and configuration for desktops.', 'Users connect via WorkSpaces clients for Windows, macOS, Linux, Chrome OS, or web.'] }], quiz: [q('What is the primary benefit of Amazon WorkSpaces?', ['Faster internet', 'Managed cloud desktops accessible from any device', 'Free software', 'Gaming performance'], 1, 'WorkSpaces delivers persistent virtual desktops that users can access securely from anywhere.')] },
  { slug: 'workspaces_advanced', name: 'WorkSpaces Advanced', description: 'Configure WorkSpaces pools, directories, and networking for enterprise desktop deployment.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Enterprise Desktop Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['WorkSpaces Pools provide non-persistent desktops for task workers and shift workers.', 'Integration with Active Directory enables single sign-on and group policy management.', 'VPC configuration ensures desktops communicate securely with corporate resources.'] }], quiz: [q('When should you use WorkSpaces Pools instead of individual WorkSpaces?', ['For power users', 'For task workers needing non-persistent sessions', 'For personal desktops', 'For gaming'], 1, "Pools provide cost-effective, non-persistent desktops for users who don't need persistent storage.")] },
  { slug: 'appstream_basics', name: 'AppStream 2.0 Basics', description: 'Stream desktop applications to any device without installing software locally.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Application Streaming', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AppStream 2.0 streams applications from AWS to any HTML5-capable browser.', 'Fleet instances run applications and stream the display to user devices.', 'Image builders create and customize application images for streaming.'] }], quiz: [q('What client do users need to access AppStream 2.0 applications?', ['Special software', 'Any HTML5-capable web browser', 'VPN client', 'Remote Desktop client'], 1, 'AppStream 2.0 streams through standard web browsers without requiring special client software.')] },
  { slug: 'appstream_fleets', name: 'AppStream 2.0 Fleets', description: 'Configure auto-scaling fleets, capacity providers, and user assignments for application delivery.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Fleet Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Fleets define the compute resources running your streamed applications.', 'Auto-scaling adjusts fleet capacity based on user demand.', 'User assignments reserve instances for specific users for guaranteed capacity.'] }], quiz: [q('What does AppStream 2.0 fleet auto-scaling do?', ['Increases instance size', 'Adds or removes instances based on user demand', 'Scales storage', 'Upgrades applications'], 1, 'Auto-scaling adjusts the number of fleet instances to match current user session requirements.')] },
  { slug: 'appstream_advanced', name: 'AppStream 2.0 Advanced', description: 'Implement S3 storage, App Blocks, and multi-tenant architectures for enterprise application hosting.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Enterprise Application Delivery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['S3 persistent storage provides user home directories accessible across sessions.', 'App Blocks package applications for deployment across multiple fleets.', 'Elastic Beanstalk integration simplifies application updates and scaling.'] }], quiz: [q('What is an App Block in AppStream 2.0?', ['A user session', 'A packaged application bundle for deployment', 'A network segment', 'A storage volume'], 1, 'App Blocks contain application files and settings that can be attached to fleets for streaming.')] },
  { slug: 'vdi_architecture', name: 'VDI Architecture', description: 'Design scalable virtual desktop infrastructure with compliance, monitoring, and cost optimization.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise VDI Design', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Directory integration enables centralized user management and policy enforcement.', 'Monitoring with CloudWatch tracks user sessions, performance, and costs.', 'Auto-stop and auto-start schedules reduce costs for non-business hours usage.'] }], quiz: [q('How can you reduce WorkSpaces costs for non-business hours?', ['Delete WorkSpaces daily', 'Configure auto-stop and auto-start schedules', 'Use smaller instance types', 'All of the above'], 3, 'Schedules automatically stop WorkSpaces outside business hours and start them when needed.')] },
];
