import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Digital Transformation',
  slug: 'digital-transformation',
  description: 'Lead organizational change with cloud adoption, agile practices, and digital innovation strategies.',
  orderIndex: 46,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'cloud_adoption', name: 'Cloud Adoption Framework', description: 'Plan and execute cloud migration with the AWS Cloud Adoption Framework methodology.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Structured Cloud Migration', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CAF provides perspectives for business, people, governance, platform, security, and operations.', 'Landing zones establish secure, multi-account environments for cloud workloads.', 'Migration strategies define how applications move from on-premises to cloud.'] }], quiz: [q('What does CAF stand for?', ['Cloud Adoption Framework', 'Computer Assisted Functions', 'Customer Application Framework', 'Central Access Facility'], 0, 'The Cloud Adoption Framework provides a structured approach for migrating to the cloud.')] },
  { slug: 'agile_practices', name: 'Agile & DevOps', description: 'Implement agile methodologies and DevOps practices for faster, more reliable software delivery.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Modern Software Delivery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Scrum and Kanban provide frameworks for iterative, collaborative development.', 'CI/CD automates build, test, and deployment processes.', 'Infrastructure as Code enables repeatable, version-controlled environments.'] }], quiz: [q('What is the primary benefit of DevOps?', ['Faster internet', 'Faster, more reliable software delivery through automation', 'Lower costs', 'Simpler code'], 1, 'DevOps breaks down silos between development and operations for continuous improvement.')] },
  { slug: 'innovation_strategy', name: 'Innovation Strategy', description: 'Build innovation capabilities with cloud-native services, experimentation, and rapid prototyping.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Cloud-Native Innovation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Serverless services reduce time-to-market for new ideas.', 'Machine learning enables data-driven product innovation.', 'Rapid prototyping validates ideas quickly with minimal investment.'] }], quiz: [q('How does serverless support innovation?', ['Faster hardware', 'Reduces operational overhead for rapid prototyping', 'Lower quality', 'More staff'], 1, 'Serverless eliminates infrastructure management, letting teams focus on building and testing ideas quickly.')] },
  { slug: 'organizational_change', name: 'Organizational Change', description: 'Manage cultural transformation with training, center of excellence, and change management practices.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Cultural Transformation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Training programs build cloud skills across the organization.', 'Centers of Excellence establish best practices and shared knowledge.', 'Change management addresses resistance and builds adoption momentum.'] }], quiz: [q('What is a Center of Excellence?', ['Physical building', 'Team that establishes best practices and shares cloud knowledge', 'Training school', 'Support desk'], 1, 'CoEs centralize expertise to guide the organization in cloud adoption and best practices.')] },
  { slug: 'data_strategy', name: 'Data-Driven Enterprise', description: 'Build analytics capabilities for business intelligence, machine learning, and data monetization.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Enterprise Data Strategy', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Data lakes centralize structured and unstructured data for analysis.', 'Business intelligence provides self-service analytics for decision makers.', 'Machine learning unlocks predictive insights from historical patterns.'] }], quiz: [q('What is a data lake?', ['Physical storage', 'Centralized repository for all types of data at any scale', 'Database only', 'Backup system'], 1, 'Data lakes store raw data in its native format, making it available for various analytics use cases.')] },
  { slug: 'digital_enterprise', name: 'Digital Enterprise', description: 'Complete digital transformation with customer experience, operational excellence, and business model innovation.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Complete Digital Transformation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Customer experience digitizes touchpoints for seamless engagement.', 'Operational excellence automates processes for efficiency gains.', 'Business model innovation creates new revenue streams from digital capabilities.'] }], quiz: [q('What is business model innovation in digital transformation?', ['Same business, new technology', 'Creating new digital revenue streams and value propositions', 'Cost cutting only', 'Hiring more staff'], 1, 'Digital transformation enables entirely new ways of creating and capturing value.')] },
];
