import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Edge Computing',
  slug: 'edge-computing',
  description: 'Process data closer to end users and devices with CloudFront, Lambda@Edge, and Wavelength.',
  orderIndex: 19,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'cloudfront_basics', name: 'Amazon CloudFront Basics', description: 'Accelerate content delivery with global CDN for static and dynamic web content.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Content Delivery Network', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CloudFront delivers content through a global network of edge locations.', 'Cache behaviors define how requests are handled for different URL patterns.', 'Origin servers provide the original content when not cached at edge.'] }], quiz: [q('What does CloudFront use to deliver content globally?', ['EC2 instances', 'Edge locations', 'S3 buckets', 'Lambda functions'], 1, 'CloudFront caches content at edge locations worldwide for low-latency delivery.')] },
  { slug: 'cloudfront_advanced', name: 'CloudFront Advanced', description: 'Configure custom SSL, origin access, and real-time logs for secure content distribution.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Advanced CDN Configuration', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Custom SSL certificates enable HTTPS with your own domain names.', 'Origin Access Control restricts S3 access to CloudFront only.', 'Real-time logs stream access data to CloudWatch or Kinesis for analysis.'] }], quiz: [q('What does Origin Access Control (OAC) do?', ['Caches content at edge', 'Restricts direct S3 access to CloudFront only', 'Enables compression', 'Blocks malicious requests'], 1, 'OAC ensures all S3 requests go through CloudFront, protecting your origin from direct access.')] },
  { slug: 'lambda_edge', name: 'Lambda@Edge', description: 'Run serverless functions at CloudFront edge locations for real-time content transformation.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Edge Computing with Lambda', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Lambda@Edge executes functions at CloudFront edge locations globally.', 'Functions can modify requests and responses before they reach the origin.', 'Use cases include authentication, A/B testing, and content personalization.'] }], quiz: [q('When can Lambda@Edge functions execute in the request/response cycle?', ['Only after origin response', 'At any point: before request, after origin, or at response', 'Only during cache misses', 'Only for HTTPS requests'], 1, 'Lambda@Edge can run at four trigger points: viewer request, origin request, origin response, and viewer response.')] },
  { slug: 'wavelength', name: 'AWS Wavelength', description: 'Deploy applications at 5G carrier edges for ultra-low latency mobile experiences.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: '5G Edge Computing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Wavelength embeds AWS compute and storage within 5G carrier networks.', 'Applications achieve single-digit millisecond latency for mobile users.', 'Wavelength Zones connect to parent AWS Regions via high-bandwidth links.'] }], quiz: [q('What is the primary benefit of AWS Wavelength?', ['Cost reduction', 'Ultra-low latency for 5G mobile applications', 'Increased storage capacity', 'Global CDN coverage'], 1, 'Wavelength places compute at the edge of 5G networks for millisecond-latency mobile experiences.')] },
  { slug: 'outposts', name: 'AWS Outposts', description: 'Run AWS infrastructure on-premises for hybrid cloud with consistent AWS experiences.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'On-Premises AWS Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Outposts delivers fully managed AWS infrastructure in your on-premises data center.', 'Uses the same APIs, hardware, and operational tools as AWS Regions.', 'Suitable for low-latency requirements and data residency constraints.'] }], quiz: [q('What makes Outposts different from EC2 on-premises?', ['Different APIs', 'Same AWS APIs and operational model as cloud regions', 'Limited service availability', 'Requires special hardware'], 1, 'Outposts provides a consistent AWS experience with the same APIs and management console as cloud regions.')] },
  { slug: 'edge_architecture', name: 'Edge Architecture Patterns', description: 'Design hybrid edge solutions with local processing, cloud synchronization, and offline resilience.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Hybrid Edge Solutions', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Local gateway appliances process data on-premises before syncing to cloud.', 'Offline-first patterns enable applications to work without constant connectivity.', 'Edge synchronization services replicate data between local and cloud storage.'] }], quiz: [q('What is an offline-first pattern?', ['Application requires constant internet', 'Application works without connectivity and syncs later', 'Data is never cached locally', 'Only cloud storage is used'], 1, 'Offline-first applications maintain functionality without connectivity and synchronize when network access is restored.')] },
];
