import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Energy & Utilities',
  slug: 'energy-smart-grid',
  description: 'Modernize energy infrastructure with smart grid, renewable integration, and IoT monitoring.',
  orderIndex: 30,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'smart_grid_basics', name: 'Smart Grid Basics', description: 'Understand intelligent grid infrastructure, demand response, and distributed energy resources.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Intelligent Grid Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Smart meters provide real-time consumption data for utilities and customers.', 'Demand response programs reduce peak load through price signals and incentives.', 'Distributed energy resources include rooftop solar, batteries, and electric vehicles.'] }], quiz: [q('What is the primary benefit of smart meters?', ['Cheaper electricity', 'Real-time consumption data for better grid management', 'Faster internet', 'Improved safety'], 1, 'Smart meters enable real-time monitoring and dynamic pricing for efficient grid operation.')] },
  { slug: 'energy_monitoring', name: 'Energy Monitoring', description: 'Collect and analyze energy data from smart meters, sensors, and SCADA systems.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Grid Data Collection', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT sensors monitor transformer health, line voltage, and grid frequency.', 'SCADA systems provide centralized control of distribution network equipment.', 'Time-series databases store high-frequency meter data for analysis and reporting.'] }], quiz: [q('What type of data do smart meters generate?', ['Daily summaries only', 'High-frequency time-series consumption data', 'Annual reports', 'Weather data'], 1, 'Smart meters generate granular time-series data enabling detailed consumption analysis.')] },
  { slug: 'renewable_integration', name: 'Renewable Integration', description: 'Integrate solar, wind, and battery storage with grid management and forecasting systems.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Clean Energy Integration', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Solar and wind generation require forecasting for grid stability management.', 'Battery energy storage systems smooth variability and provide peak shaving.', 'Virtual power plants aggregate distributed resources for grid services.'] }], quiz: [q('What is a virtual power plant?', ['A physical power station', 'Aggregation of distributed energy resources for grid services', 'A backup generator', 'A nuclear facility'], 1, 'Virtual power plants coordinate many small energy resources to act as a single power plant.')] },
  { slug: 'grid_analytics', name: 'Grid Analytics', description: 'Apply machine learning to predict outages, optimize maintenance, and balance supply-demand.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Intelligent Grid Operations', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Predictive maintenance identifies equipment likely to fail before outages occur.', 'Load forecasting predicts demand patterns for optimal generation scheduling.', 'Outage detection uses smart meter data to pinpoint故障 locations automatically.'] }], quiz: [q('How does predictive maintenance benefit utilities?', ['Increases outages', 'Prevents equipment failures and reduces downtime', 'Raises costs', 'Simplifies operations'], 1, 'Predictive maintenance prevents outages by identifying and addressing equipment issues proactively.')] },
  { slug: 'energy_ai', name: 'Energy AI', description: 'Deploy AI for load forecasting, asset optimization, and autonomous grid management.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Grid Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Deep learning models predict solar and wind generation from weather patterns.', 'Reinforcement learning optimizes battery charge/discharge cycles automatically.', 'Computer vision inspects power lines and equipment for damage detection.'] }], quiz: [q('What AI technique optimizes battery storage automatically?', ['Linear regression', 'Reinforcement learning', 'Decision trees', 'K-means clustering'], 1, 'Reinforcement learning learns optimal battery strategies through trial and error in simulations.')] },
  { slug: 'utility_enterprise', name: 'Utility Enterprise', description: 'Integrate grid operations with customer service, billing, and regulatory compliance systems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Digital Utility Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Customer information systems manage billing, payments, and service requests.', 'Regulatory reporting automates compliance submissions to energy commissions.', 'DERMS manages distributed energy resources for grid optimization and customer programs.'] }], quiz: [q('What does DERMS stand for?', ['Distribution Energy Resource Management System', 'Data Encryption and Recovery Management Service', 'Dynamic Event Response Monitoring System', 'Direct Energy Retail Market Standard'], 0, 'DERMS coordinates distributed energy resources like solar, batteries, and EVs for grid services.')] },
];
