import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Financial Services',
  slug: 'financial-services',
  description: 'Build secure, compliant financial applications with banking, payments, and fintech solutions.',
  orderIndex: 26,
  theme: 'CITADEL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'fintech_basics', name: 'FinTech Fundamentals', description: 'Understand digital banking, payment processing, and financial technology patterns.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Financial Technology Landscape', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Digital banking replaces physical branches with cloud-native applications.', 'Payment processing requires PCI DSS compliance for card data security.', 'API-first design enables integration with banking cores and payment networks.'] }], quiz: [q('What compliance standard applies to payment card data?', ['HIPAA', 'PCI DSS', 'SOC 2', 'GDPR'], 1, 'PCI DSS specifies security requirements for handling credit card and debit card information.')] },
  { slug: 'banking_aws', name: 'Banking on AWS', description: 'Deploy core banking systems with high availability, encryption, and regulatory compliance.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Cloud-Native Banking', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Multi-AZ deployments ensure banking applications meet 99.99% availability requirements.', 'Encryption at rest with KMS and in transit with TLS protects customer financial data.', 'Audit logging with CloudTrail provides immutable records for regulatory examination.'] }], quiz: [q('Why is multi-AZ deployment critical for banking?', ['Cost savings', 'Meets 99.99% availability for financial transactions', 'Faster performance', 'Simpler architecture'], 1, 'Financial services require extremely high availability to prevent revenue loss and regulatory penalties.')] },
  { slug: 'payment_processing', name: 'Payment Processing', description: 'Build PCI-compliant payment systems with tokenization and fraud detection.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Secure Payment Systems', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Payment tokenization replaces card numbers with non-reversible tokens.', 'Fraud detection uses machine learning to identify suspicious transactions.', 'PCI scope reduction isolates card data in dedicated compliant environments.'] }], quiz: [q('What is payment tokenization?', ['Encrypting card numbers', 'Replacing sensitive card data with non-reversible tokens', 'Storing cards in databases', 'Sending cards over HTTPS'], 1, 'Tokenization removes sensitive card data from your environment by replacing it with unique identifiers.')] },
  { slug: 'trading_platforms', name: 'Trading Platforms', description: 'Build low-latency trading systems with real-time market data and order execution.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'High-Frequency Trading Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Low-latency networking enables sub-millisecond trade execution.', 'Market data feeds provide real-time price information for trading algorithms.', 'Risk management systems validate orders before execution to prevent losses.'] }], quiz: [q('What is the primary concern for trading platform architecture?', ['Low cost', 'Ultra-low latency', 'High memory', 'Large storage'], 1, 'Trading platforms require minimal latency to execute orders before market conditions change.')] },
  { slug: 'regtech', name: 'RegTech Compliance', description: 'Automate regulatory reporting, KYC, and AML compliance with cloud-native solutions.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Regulatory Technology', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['KYC verification validates customer identity using document analysis and database checks.', 'AML monitoring detects suspicious transaction patterns in real-time.', 'Regulatory reporting automates submission of compliance data to authorities.'] }], quiz: [q('What does KYC stand for?', ['Keep Your Cash', 'Know Your Customer', 'Key Your Computer', 'Kernel Your Code'], 1, 'KYC regulations require financial institutions to verify customer identities before conducting business.')] },
  { slug: 'fintech_enterprise', name: 'Enterprise FinTech', description: 'Design scalable financial platforms with microservices, event sourcing, and CQRS patterns.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Modern Financial Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Event sourcing stores all changes as immutable events for complete audit trails.', 'CQRS separates read and write models for optimized financial data access.', 'Microservices decompose banking functions for independent scaling and deployment.'] }], quiz: [q('Why is event sourcing valuable for financial systems?', ['Faster queries', 'Complete immutable audit trail of all transactions', 'Lower costs', 'Simpler code'], 1, 'Event sourcing maintains a complete history of all changes, critical for financial auditing and compliance.')] },
];
