import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Food & Beverage',
  slug: 'food-supply',
  description: 'Manage food supply chains with cold chain monitoring, inventory tracking, and safety compliance.',
  orderIndex: 40,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'cold_chain', name: 'Cold Chain Monitoring', description: 'Track temperature-sensitive products throughout the supply chain with IoT sensors.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Temperature Monitoring', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT sensors monitor temperature, humidity, and location during transport.', 'Real-time alerts notify when conditions exceed safe thresholds.', 'Historical data provides complete chain of custody documentation.'] }], quiz: [q('Why is cold chain monitoring critical?', ['Cost savings', 'Prevents spoilage of temperature-sensitive products', 'Faster delivery', 'Better marketing'], 1, 'Cold chain monitoring ensures products remain within safe temperature ranges to prevent spoilage.')] },
  { slug: 'inventory_management', name: 'Inventory Management', description: 'Optimize food inventory with FIFO tracking, expiration management, and demand forecasting.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Food Inventory Systems', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['FIFO tracking ensures oldest products ship first to minimize waste.', 'Expiration management prevents distribution of expired products.', 'Demand forecasting reduces overstock and stockouts for perishable items.'] }], quiz: [q('What does FIFO stand for in inventory?', ['First In First Out', 'Freezer Inventory For Operations', 'Food Inspection and Fulfillment Order', 'Fresh Inventory Tracking Only'], 0, 'FIFO ensures oldest inventory ships first, critical for perishable food products.')] },
  { slug: 'food_safety', name: 'Food Safety Compliance', description: 'Manage HACCP, FSMA, and food safety certifications with digital documentation systems.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Food Safety Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['HACCP plans identify and control food safety hazards at critical points.', 'FSMA compliance requires preventive controls and hazard analysis documentation.', 'Digital records simplify audit preparation and regulatory inspections.'] }], quiz: [q('What does HACCP stand for?', ['Hazard Analysis Critical Control Points', 'Health and Safety Compliance Program', 'Hazard and Contamination Control Protocol', 'Food Safety Certification'], 0, 'HACCP is a systematic approach to identifying and controlling food safety hazards.')] },
  { slug: 'restaurant_tech', name: 'Restaurant Technology', description: 'Deploy POS systems, online ordering, and kitchen management with cloud platforms.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Digital Restaurant Operations', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Cloud POS systems process orders and payments with real-time reporting.', 'Online ordering platforms handle delivery and pickup orders.', 'Kitchen display systems optimize food preparation workflows.'] }], quiz: [q('What is the benefit of cloud POS systems?', ['Cheaper hardware', 'Real-time reporting and remote management capabilities', 'Faster internet', 'Better food quality'], 1, 'Cloud POS provides real-time data access and management from anywhere with internet connectivity.')] },
  { slug: 'food_ai', name: 'Food AI', description: 'Apply machine learning to demand prediction, quality inspection, and menu optimization.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI in Food Industry', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Demand prediction reduces food waste by forecasting accurate order quantities.', 'Computer vision inspects food quality and identifies defects automatically.', 'Menu optimization analyzes sales data to improve profitability and customer satisfaction.'] }], quiz: [q('How does AI reduce food waste?', ['Larger portions', 'Accurate demand forecasting and inventory optimization', 'Faster cooking', 'Better packaging'], 1, 'AI predicts demand more accurately, reducing overproduction and spoilage in food operations.')] },
  { slug: 'food_enterprise', name: 'Food Enterprise', description: 'Scale food operations with multi-location management, supply chain integration, and franchise systems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise Food Operations', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Multi-location platforms standardize operations across restaurant chains.', 'Supply chain integration automates ordering based on inventory levels.', 'Franchise management systems ensure consistency and compliance.'] }], quiz: [q('What is multi-location food management?', ['Single restaurant only', 'Standardizing operations across multiple restaurant locations', 'Home cooking', 'Food delivery only'], 1, 'Multi-location systems ensure consistent quality, pricing, and operations across all restaurant locations.')] },
];
