import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Game Development',
  slug: 'game-development',
  description: 'Build, deploy, and scale games with GameLift, Lumberyard, and cloud gaming solutions.',
  orderIndex: 32,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'game_cloud_basics', name: 'Game Cloud Basics', description: 'Understand cloud gaming architecture, multiplayer infrastructure, and backend services.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Cloud Gaming Foundation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Cloud backends handle player authentication, leaderboards, and matchmaking.', 'Dedicated servers provide consistent low-latency multiplayer experiences.', 'Cloud saves enable players to continue progress across devices.'] }], quiz: [q('Why use dedicated servers for multiplayer games?', ['Cheaper', 'Consistent low-latency experience for all players', 'Easier to develop', 'No internet required'], 1, 'Dedicated servers provide equal latency for all players and prevent cheating.')] },
  { slug: 'gamelift', name: 'Amazon GameLift', description: 'Deploy and scale multiplayer game servers with managed hosting and player matching.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Managed Game Server Hosting', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GameLift FlexMatch provides custom matchmaking with player skill and latency matching.', 'FleetIQ optimizes costs by using Spot Instances for game server hosting.', 'Auto-scaling adjusts server capacity based on player demand in real-time.'] }], quiz: [q('What is FlexMatch?', ['Game engine', 'Customizable matchmaking service for multiplayer games', 'Graphics library', 'Audio engine'], 1, 'FlexMatch creates custom matching rules based on player skills, latency, and group requirements.')] },
  { slug: 'multiplayer_networking', name: 'Multiplayer Networking', description: 'Implement real-time game networking with state synchronization and lag compensation.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Real-Time Game Networking', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Client-server architecture prevents cheating by validating all actions server-side.', 'State synchronization ensures all players see consistent game world updates.', 'Lag compensation techniques mask network latency for smoother gameplay.'] }], quiz: [q('Why is client-server architecture preferred for multiplayer?', ['Faster development', 'Prevents cheating by validating actions server-side', 'Uses less bandwidth', 'Simpler code'], 1, 'Server-side validation ensures all game state changes are legitimate and prevents client manipulation.')] },
  { slug: 'game_analytics', name: 'Game Analytics', description: 'Track player behavior, optimize monetization, and improve retention with data analytics.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Player Behavior Analytics', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Event tracking captures player actions for behavior analysis.', 'Funnel analysis identifies where players drop out of progression.', 'A/B testing measures the impact of game changes on player engagement.'] }], quiz: [q('What is funnel analysis in gaming?', ['Water feature design', 'Identifying where players abandon progression', 'Audio mixing', 'Level design'], 1, 'Funnel analysis tracks player progression through key milestones to identify friction points.')] },
  { slug: 'game_ai', name: 'Game AI', description: 'Implement intelligent NPCs, procedural generation, and dynamic difficulty adjustment.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Intelligent Game Systems', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Behavior trees create complex NPC decision-making patterns.', 'Procedural generation creates unique game content algorithmically.', 'Dynamic difficulty adjusts challenge based on player skill and engagement.'] }], quiz: [q('What is procedural generation?', ['Manual level design', 'Algorithmic creation of game content', 'Pre-rendered graphics', 'Scripted events'], 1, 'Procedural generation uses algorithms to create unique game worlds, levels, and content automatically.')] },
  { slug: 'game_enterprise', name: 'Game Enterprise', description: 'Scale game operations with live services, anti-cheat systems, and global infrastructure.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Live Game Operations', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Live services deliver continuous content updates and seasonal events.', 'Anti-cheat systems detect and prevent unfair gameplay advantages.', 'Global deployment ensures low-latency access for players worldwide.'] }], quiz: [q('What are live services in gaming?', ['One-time release', 'Continuous content updates and events after launch', 'Beta testing', 'Game development tools'], 1, 'Live services keep games engaging with ongoing content, events, and community features post-launch.')] },
];
