import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Government & Public Sector',
  slug: 'government-compliance',
  description: 'Deploy compliant government workloads with GovCloud, FedRAMP, and security baselines.',
  orderIndex: 35,
  theme: 'CITADEL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'govcloud_basics', name: 'AWS GovCloud Basics', description: 'Understand isolated cloud regions for US government workloads and compliance requirements.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Government Cloud Regions', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GovCloud provides isolated regions operated by US persons for sensitive workloads.', 'FedRAMP authorization certifies AWS for federal government cloud adoption.', 'ITAR compliance supports defense and aerospace data requirements.'] }], quiz: [q('Who can access AWS GovCloud regions?', ['Anyone', 'US persons and organizations only', 'Government employees only', 'Military only'], 1, 'GovCloud restricts access to US persons to meet federal compliance requirements.')] },
  { slug: 'fedramp', name: 'FedRAMP Compliance', description: 'Navigate Federal Risk and Authorization Management Program requirements for cloud services.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Federal Cloud Authorization', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['FedRAMP provides a standardized approach to cloud security assessment.', 'Authorization packages document security controls for agency review.', 'Continuous monitoring ensures ongoing compliance with federal requirements.'] }], quiz: [q('What is the purpose of FedRAMP?', ['Reduce costs', 'Standardize cloud security assessment for federal agencies', 'Speed up development', 'Improve performance'], 1, 'FedRAMP creates consistent security standards for federal cloud adoption and procurement.')] },
  { slug: 'public_sector', name: 'Public Sector Solutions', description: 'Deploy citizen services, digital government, and public safety applications on AWS.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Digital Government', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Citizen portals provide online access to government services and information.', 'Digital identity systems enable secure authentication for government services.', 'Open data platforms make public information accessible for transparency.'] }], quiz: [q('What is a citizen portal?', ['Social media site', 'Online platform for accessing government services', 'News website', 'Gaming platform'], 1, 'Citizen portals digitize government services, allowing online access to permits, payments, and information.')] },
  { slug: 'security_baseline', name: 'Security Baselines', description: 'Implement STIG hardening, CIS benchmarks, and compliance frameworks for government systems.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'System Hardening Standards', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['STIGs provide security configuration guidelines for DoD systems.', 'CIS benchmarks offer industry-accepted security best practices.', 'AWS Systems Manager Automates security baseline enforcement across instances.'] }], quiz: [q('What do STIGs provide?', ['Software updates', 'Security configuration guidelines for DoD systems', 'Hardware specifications', 'Training materials'], 1, 'STIGs define security requirements for hardening systems to meet DoD compliance standards.')] },
  { slug: 'government_ai', name: 'Government AI', description: 'Apply AI responsibly in public sector with transparency, fairness, and accountability requirements.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Responsible AI in Government', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Explainable AI provides transparency for government decision-making processes.', 'Bias detection ensures AI systems treat all citizens fairly.', 'Audit trails maintain accountability for automated government actions.'] }], quiz: [q('Why is explainable AI important in government?', ['Faster processing', 'Transparency and accountability in government decisions', 'Lower costs', 'Better graphics'], 1, 'Government AI decisions affecting citizens require transparency and the ability to explain outcomes.')] },
  { slug: 'government_enterprise', name: 'Government Enterprise', description: 'Modernize legacy government systems with cloud migration, DevSecOps, and shared services.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Government Modernization', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Legacy modernization migrates mainframe and COBOL systems to cloud architectures.', 'DevSecOps integrates security into government software development lifecycles.', 'Shared services platforms reduce duplication across government agencies.'] }], quiz: [q('What is DevSecOps?', ['Development only', 'Integrating security into software development and operations', 'Security team operations', 'Dev testing'], 1, 'DevSecOps embeds security practices throughout the software development and deployment pipeline.')] },
];
