import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Healthcare & Life Sciences',
  slug: 'healthcare-compliance',
  description: 'Build HIPAA-compliant healthcare applications with medical imaging, genomics, and FHIR solutions.',
  orderIndex: 27,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'hipaa_basics', name: 'HIPAA Compliance Basics', description: 'Understand HIPAA requirements for protecting electronic protected health information (ePHI).', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Healthcare Data Protection', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['HIPAA requires safeguards for electronic protected health information (ePHI).', 'AWS services can be configured as HIPAA-eligible for healthcare workloads.', 'Business Associate Agreements (BAAs) define data protection responsibilities.'] }], quiz: [q('What does ePHI stand for?', ['Electronic Protected Health Information', 'Encrypted Personal Health Exchange', 'Electronic Public Health Index', 'Enhanced Privacy Healthcare Integration'], 0, 'ePHI is electronically stored or transmitted health information that requires HIPAA protection.')] },
  { slug: 'healthcare_aws', name: 'Healthcare on AWS', description: 'Deploy HIPAA-eligible services for electronic health records and clinical applications.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'HIPAA-Eligible Services', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Amazon EC2, S3, and RDS are HIPAA-eligible when configured properly.', 'Encryption at rest and in transit protects ePHI from unauthorized access.', 'Access logging and audit trails demonstrate compliance during examinations.'] }], quiz: [q('Which AWS service provides encryption key management for HIPAA compliance?', ['IAM', 'KMS', 'CloudWatch', 'Route 53'], 1, 'KMS manages encryption keys with FIPS 140-2 validation for protecting ePHI at rest.')] },
  { slug: 'fhir', name: 'FHIR on AWS', description: 'Implement Fast Healthcare Interoperability Resources for health data exchange.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Health Data Interoperability', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['FHIR is the modern standard for exchanging healthcare information electronically.', 'AWS HealthLake stores and queries FHIR-formatted health data.', 'Smart on FHIR enables patient authorization for third-party application access.'] }], quiz: [q('What is FHIR?', ['A database format', 'Fast Healthcare Interoperability Resources standard', 'An encryption method', 'A programming language'], 1, 'FHIR is an HL7 standard for exchanging healthcare information using modern web technologies.')] },
  { slug: 'medical_imaging', name: 'Medical Imaging', description: 'Process and store DICOM images with AI-powered analysis and scalable cloud storage.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'DICOM Image Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Amazon HealthLake Imaging processes DICOM images with ML-powered analysis.', 'DICOMweb APIs enable standard access to medical images and metadata.', 'PACS integration connects cloud imaging with existing clinical workflows.'] }], quiz: [q('What file format is used for medical images?', ['JPEG', 'DICOM', 'PNG', 'PDF'], 1, 'DICOM is the international standard format for medical images like X-rays, CT scans, and MRIs.')] },
  { slug: 'genomics', name: 'Genomics on AWS', description: 'Analyze genomic data with scalable compute and specialized bioinformatics tools.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Genomic Data Analysis', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS Batch and Lambda provide scalable compute for genome sequencing pipelines.', 'Genomics data stores petabytes of sequence data with cost-effective storage tiers.', 'Machine learning identifies genetic variants and predicts disease risk factors.'] }], quiz: [q('Why is cloud computing important for genomics?', ['Cheaper hardware', 'Massive parallel processing for genome analysis', 'Simpler software', 'Better displays'], 1, 'Genome analysis requires massive compute resources that scale elastically in the cloud.')] },
  { slug: 'healthcare_ai', name: 'Healthcare AI', description: 'Apply machine learning to clinical data for diagnosis support, drug discovery, and patient outcomes.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'AI-Powered Healthcare', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['SageMaker trains models on clinical data for diagnostic decision support.', 'Comprehend Medical extracts medical information from unstructured clinical notes.', 'Computer vision analyzes medical images for abnormality detection.'] }], quiz: [q('Which AWS service extracts information from clinical notes?', ['Rekognition', 'Comprehend Medical', 'Textract', 'Polly'], 1, 'Comprehend Medical identifies medical conditions, medications, and procedures in clinical text.')] },
];
