import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Infrastructure as Code',
  slug: 'infrastructure-as-code',
  description: 'Define and provision cloud infrastructure using code with CloudFormation, CDK, and Terraform.',
  orderIndex: 13,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'cloudformation_basics', name: 'CloudFormation Basics', description: 'Define AWS infrastructure as JSON or YAML templates for repeatable, version-controlled deployments.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Template-Based Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CloudFormation templates describe the desired state of your AWS resources.', 'Stacks are the unit of deployment — create, update, or delete a collection of resources together.', 'Template parameters allow customization without modifying the base template.'] }], quiz: [q('What is a CloudFormation stack?', ['A single EC2 instance', 'A collection of AWS resources managed as a single unit', 'A Docker container', 'A Lambda function'], 1, 'A stack is a group of AWS resources created, updated, or deleted together from a CloudFormation template.')] },
  { slug: 'cdk_fundamentals', name: 'AWS CDK Fundamentals', description: 'Define cloud infrastructure using familiar programming languages with the AWS Cloud Development Kit.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Programming-Language Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CDK lets you define infrastructure using TypeScript, Python, Java, Go, or .NET.', 'Constructs are reusable components that abstract AWS resource configurations.', 'CDK synthesizes your code into CloudFormation templates for deployment.'] }], quiz: [q('What are CDK constructs?', ['Docker images', 'Reusable components that abstract AWS resource configurations', 'IAM policies', 'CloudFormation stacks'], 1, 'Constructs are the building blocks of CDK applications, encapsulating one or more AWS resources with sensible defaults.')] },
  { slug: 'cloudformation_advanced', name: 'CloudFormation Advanced', description: 'Master nested stacks, stack sets, drift detection, and custom resources for complex deployments.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Advanced Template Patterns', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Nested stacks break large templates into manageable, reusable components.', 'StackSets deploy stacks across multiple AWS accounts and regions.', 'Drift detection identifies resources modified outside of CloudFormation.'] }], quiz: [q('What does CloudFormation drift detection identify?', ['Cost overruns', 'Resources modified outside CloudFormation management', 'Security vulnerabilities', 'Performance bottlenecks'], 1, 'Drift detection compares the actual resource state with the template to find manual changes made outside CloudFormation.')] },
  { slug: 'cdk_advanced', name: 'CDK Advanced Patterns', description: 'Build reusable constructs, manage app stacks, and implement testing strategies for CDK applications.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Reusable Constructs and Testing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['L3 constructs (constructs of constructs) encapsulate entire architectural patterns.', 'CDK assertions library enables unit testing of infrastructure code before deployment.', 'Aspects apply cross-cutting concerns like tagging or encryption to all resources in a stack.'] }], quiz: [q('What is the purpose of CDK Aspects?', ['Deploy stacks to production', 'Apply cross-cutting concerns like tagging to all resources', 'Monitor stack performance', 'Delete unused stacks'], 1, 'Aspects traverse the construct tree and apply modifications like adding tags or enforcing encryption policies.')] },
  { slug: 'iac_testing', name: 'IaC Testing Strategies', description: 'Validate infrastructure code with unit tests, integration tests, and compliance checks before deployment.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Testing Infrastructure Code', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Structural tests validate template syntax and resource properties without deploying.', 'Integration tests deploy stacks and verify actual resource configurations.', 'Policy-as-code tools like cfn-nag and Checkov scan templates for security misconfigurations.'] }], quiz: [q('What type of IaC test deploys resources to verify they work correctly?', ['Unit test', 'Structural test', 'Integration test', 'Lint check'], 2, 'Integration tests create real resources in a test account and validate their actual configurations and behaviors.')] },
  { slug: 'multi_account_iac', name: 'Multi-Account IaC', description: 'Manage infrastructure across multiple AWS accounts and environments with controlled promotion strategies.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise Infrastructure Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Landing zones provide a pre-configured multi-account structure using AWS Control Tower.', 'StackSets with service-managed permissions automatically deploy across organizational accounts.', 'Environment promotion moves infrastructure changes through dev, staging, and production accounts.'] }], quiz: [q('What is an AWS Landing Zone?', ['A single EC2 instance', 'A pre-configured multi-account environment with security baseline', 'A CloudFormation template', 'A CI/CD pipeline'], 1, 'A Landing Zone is a well-architected multi-account environment that provides security, networking, and identity baselines.')] },
];
