import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Internet of Things',
  slug: 'iot-core',
  description: 'Connect, manage, and secure IoT devices at scale with AWS IoT Core and device services.',
  orderIndex: 48,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'iot_basics', name: 'IoT Fundamentals', description: 'Understand IoT architectures, device protocols, and edge-to-cloud connectivity patterns.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Connected Device Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT connects physical devices to the cloud for data collection and control.', 'MQTT and HTTP are common protocols for device-to-cloud communication.', 'Device shadows maintain virtual representations of device state.'] }], quiz: [q('What is MQTT in IoT?', ['A database', 'Lightweight messaging protocol for constrained devices', 'An operating system', 'A programming language'], 1, 'MQTT is a lightweight publish-subscribe protocol designed for constrained devices and networks.')] },
  { slug: 'iot_core', name: 'AWS IoT Core', description: 'Connect billions of devices with managed MQTT and HTTPS message brokers.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Managed IoT Messaging', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT Core provides a managed message broker for MQTT and HTTPS.', 'Thing shadows store device state for offline access and synchronization.', 'Rules engine routes messages to other AWS services automatically.'] }], quiz: [q('What does AWS IoT Core provide?', ['Physical hardware', 'Managed message broker for device connectivity', 'Cloud storage', 'Web hosting'], 1, 'IoT Core manages the messaging infrastructure connecting devices to the cloud.')] },
  { slug: 'device_management', name: 'Device Management', description: 'Register, organize, and monitor IoT devices with fleet management and remote operations.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Fleet Device Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Device registration provisions and authenticates devices at scale.', 'Fleet indexing enables search and query across device attributes.', 'Remote actions push commands to devices for configuration and updates.'] }], quiz: [q('What is fleet indexing in IoT?', ['Device storage', 'Enables search and query across device attributes', 'Network configuration', 'Security protocol'], 1, 'Fleet indexing creates searchable indexes of device data for monitoring and management.')] },
  { slug: 'iot_analytics', name: 'IoT Analytics', description: 'Process, analyze, and visualize IoT data with managed analytics pipelines.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'IoT Data Processing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT Analytics pipelines clean, filter, and transform raw device data.', 'Data stores maintain historical IoT data for analysis and dashboards.', 'Notebooks provide interactive analysis of IoT datasets.'] }], quiz: [q('What do IoT Analytics pipelines do?', ['Store data only', 'Clean, filter, and transform raw device data', 'Send commands', 'Manage devices'], 1, 'Pipelines preprocess raw IoT data to prepare it for analysis and visualization.')] },
  { slug: 'iot_security', name: 'IoT Security', description: 'Implement device authentication, certificate management, and security policies for IoT.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Device Security', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['X.509 certificates provide strong device authentication.', 'IoT policies define fine-grained permissions for device actions.', 'Device Defender detects anomalous device behavior and security issues.'] }], quiz: [q('What authentication method does IoT Core use by default?', ['Passwords', 'X.509 certificates', 'API keys', 'OAuth tokens'], 1, 'X.509 certificates provide mutual authentication between devices and IoT Core.')] },
  { slug: 'iot_enterprise', name: 'IoT Enterprise', description: 'Scale IoT solutions with edge computing, digital twins, and industry-specific platforms.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise IoT Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT Greengrass runs Lambda functions and ML inference at the edge.', 'IoT TwinMaker creates digital twins from IoT device data.', 'Industry platforms provide pre-built solutions for manufacturing, healthcare, and smart cities.'] }], quiz: [q('What is IoT TwinMaker?', ['Device simulator', 'Creates digital twins from IoT device data', 'Security service', 'Analytics tool'], 1, 'TwinMaker builds digital twins that mirror physical devices for simulation and monitoring.')] },
];
