import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Legal & Compliance',
  slug: 'legal-discovery',
  description: 'Manage legal hold, e-discovery, and data retention with cloud-native compliance solutions.',
  orderIndex: 36,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'edisclosure_basics', name: 'E-Discovery Basics', description: 'Understand electronic discovery, legal holds, and document review processes for litigation.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Electronic Discovery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['E-discovery identifies, collects, and produces electronically stored information.', 'Legal holds preserve relevant data when litigation is reasonably anticipated.', 'Document review categorizes and prioritizes responsive documents for production.'] }], quiz: [q('What is a legal hold?', ['Document storage', 'Preservation of relevant data when litigation is anticipated', 'Court order', 'Backup strategy'], 1, 'Legal holds require organizations to preserve all potentially relevant electronic information.')] },
  { slug: 'data_retention', name: 'Data Retention', description: 'Implement automated retention policies for regulatory compliance and litigation readiness.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Information Governance', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Retention policies define how long different types of data must be preserved.', 'Automated deletion enforces retention schedules to reduce storage costs.', 'Classification systems identify sensitive and regulated data for appropriate handling.'] }], quiz: [q('Why automate data retention?', ['Faster deletion', 'Consistent enforcement of retention policies and compliance', 'Lower quality', 'Manual review is better'], 1, 'Automation ensures consistent policy enforcement and reduces human error in data management.')] },
  { slug: 'cloud_evidence', name: 'Cloud Evidence Collection', description: 'Collect and preserve electronic evidence from cloud services with proper chain of custody.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Digital Forensics', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CloudTrail logs provide audit trails of user actions in AWS services.', 'S3 object versioning preserves deleted or modified files for investigation.', 'Forensic imaging captures point-in-time snapshots of cloud resources.'] }], quiz: [q('What AWS service provides audit trails for investigations?', ['CloudWatch', 'CloudTrail', 'IAM', 'VPC'], 1, 'CloudTrail records API calls and user actions for security investigation and compliance.')] },
  { slug: 'compliance_automation', name: 'Compliance Automation', description: 'Automate compliance monitoring, evidence collection, and audit preparation with AWS tools.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Continuous Compliance', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS Config monitors resource configurations against compliance rules.', 'Security Hub aggregates findings from multiple security services.', 'Automated evidence collection simplifies audit preparation and response.'] }], quiz: [q('What does AWS Config monitor?', ['Network traffic', 'Resource configurations against compliance rules', 'User login times', 'Cost spending'], 1, 'AWS Config continuously tracks resource configurations and evaluates them against compliance rules.')] },
  { slug: 'legal_ai', name: 'Legal AI', description: 'Apply machine learning to contract analysis, legal research, and document classification.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Legal Tech', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Comprehend extracts key terms and obligations from legal contracts.', 'Textract analyzes scanned legal documents for data extraction.', 'Custom classifiers categorize documents by legal relevance and privilege.'] }], quiz: [q('How does AI help contract analysis?', ['Replaces lawyers', 'Automates extraction of key terms and obligations', 'Writes contracts', 'Manages court filings'], 1, 'AI accelerates contract review by automatically identifying important clauses and obligations.')] },
  { slug: 'legal_enterprise', name: 'Legal Enterprise', description: 'Integrate legal technology with case management, billing, and client relationship systems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Legal Operations Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Case management systems track matter progress and deadlines.', 'E-billing platforms manage legal spend and invoice processing.', 'Client portals provide secure access to case documents and status updates.'] }], quiz: [q('What is e-billing in legal operations?', ['Email billing', 'Electronic management of legal invoices and spend', 'Online payment', 'Digital contracts'], 1, 'E-billing automates legal invoice processing, tracking, and budget management.')] },
];
