import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Logistics & Supply Chain',
  slug: 'logistics-tracking',
  description: 'Optimize supply chain operations with real-time tracking, warehouse automation, and demand planning.',
  orderIndex: 43,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'supply_chain_basics', name: 'Supply Chain Basics', description: 'Understand procurement, logistics, inventory management, and distribution workflows.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Supply Chain Fundamentals', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Procurement manages supplier relationships and purchase orders.', 'Logistics coordinates transportation and warehousing of goods.', 'Inventory management balances stock levels with demand forecasts.'] }], quiz: [q('What is the primary goal of supply chain management?', ['Reduce employees', 'Optimize flow of goods from suppliers to customers', 'Increase storage', 'Simplify processes'], 1, 'Supply chain management ensures efficient movement of products from origin to consumption.')] },
  { slug: 'warehouse_automation', name: 'Warehouse Automation', description: 'Deploy robotics, AS/RS systems, and ML-powered picking optimization in distribution centers.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Automated Distribution Centers', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Autonomous mobile robots transport products through warehouse aisles.', 'Automated storage and retrieval systems optimize vertical space usage.', 'ML picking algorithms optimize the sequence of items to collect.'] }], quiz: [q('What is an AS/RS system?', ['Accounting software', 'Automated Storage and Retrieval System', 'Customer service', 'Sales tracking'], 1, 'AS/RS systems automatically store and retrieve products using robotic mechanisms and conveyors.')] },
  { slug: 'realtime_tracking', name: 'Real-Time Tracking', description: 'Monitor shipments with GPS, IoT sensors, and blockchain for supply chain visibility.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Supply Chain Visibility', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GPS tracking provides real-time shipment location and ETA predictions.', 'IoT sensors monitor conditions like temperature, humidity, and shock.', 'Blockchain creates immutable records of custody transfers and certifications.'] }], quiz: [q('What does blockchain provide in supply chain tracking?', ['Faster shipping', 'Immutable records of custody transfers', 'Lower costs', 'Better packaging'], 1, 'Blockchain creates tamper-proof records of product movement and ownership throughout the supply chain.')] },
  { slug: 'demand_planning', name: 'Demand Planning', description: 'Forecast demand with machine learning, seasonality analysis, and promotional impact modeling.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Predictive Demand Forecasting', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['ML models analyze historical sales and external factors for demand prediction.', 'Seasonality patterns account for predictable demand fluctuations.', 'Promotional modeling estimates the impact of marketing campaigns on demand.'] }], quiz: [q('What factors influence demand forecasting?', ['Only past sales', 'Historical data, seasonality, promotions, and external factors', 'Only weather', 'Only competitor actions'], 1, 'Accurate forecasting considers multiple factors including history, trends, promotions, and external conditions.')] },
  { slug: 'logistics_ai', name: 'Logistics AI', description: 'Apply machine learning to route optimization, carrier selection, and predictive logistics.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Logistics', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Route optimization algorithms find the most efficient delivery paths.', 'Carrier selection ML chooses the best shipping option for each shipment.', 'Predictive logistics anticipates delays and proactively reroutes shipments.'] }], quiz: [q('How does AI optimize delivery routes?', ['Manual planning', 'Algorithms find the most efficient paths considering constraints', 'Random selection', 'Driver preference only'], 1, 'AI algorithms consider traffic, weather, delivery windows, and vehicle capacity to optimize routes.')] },
  { slug: 'logistics_enterprise', name: 'Logistics Enterprise', description: 'Scale supply chain operations with multi-warehouse, 3PL integration, and global trade management.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise Supply Chain', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Multi-warehouse platforms coordinate inventory across distribution centers.', '3PL integration connects with external logistics providers.', 'Global trade management handles customs, duties, and international regulations.'] }], quiz: [q('What is 3PL integration?', ['Third Party Logistics - connecting with external providers', 'Three Product Lines', 'Three Phase Loading', 'Third Party Licensing'], 0, '3PL integration connects internal systems with third-party logistics providers for fulfillment.')] },
];
