import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Mainframe Modernization',
  slug: 'mainframe-modernization',
  description: 'Migrate and modernize mainframe workloads with AWS tools for COBOL, batch processing, and legacy integration.',
  orderIndex: 24,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'mainframe_basics', name: 'Mainframe Fundamentals', description: 'Understand COBOL, JCL, CICS, and batch processing on z/OS mainframes.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Legacy System Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['COBOL processes business logic for financial and transaction systems.', 'JCL defines batch job execution sequences and resource requirements.', 'CICS handles online transaction processing for real-time applications.'] }], quiz: [q('What does CICS stand for?', ['Customer Information Control System', 'Computer Internet Computing Service', 'Cloud Infrastructure Configuration Service', 'Centralized Information Control System'], 0, 'CICS is an IBM transaction processing system for online business applications.')] },
  { slug: 'cloudmainframe_basics', name: 'AWS Mainframe Modernization', description: 'Discover, analyze, and transform mainframe applications with automated migration tools.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Migration Discovery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Mainframe Modernization Portal analyzes COBOL code for migration readiness.', 'Automated refactoring converts COBOL to Java or .NET applications.', 'Rehosting runs mainframe workloads on AWS with minimal code changes.'] }], quiz: [q('What is the first step in mainframe modernization?', ['Rewrite all code', 'Discover and analyze existing applications', 'Delete the mainframe', 'Train new developers'], 1, 'Discovery analyzes code complexity, dependencies, and business value to plan migration strategy.')] },
  { slug: 'blu_age', name: 'Blu Age Automated Refactoring', description: 'Convert COBOL, PL/I, and Assembler applications to Java and .NET with automated tools.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Automated Code Transformation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Blu Age transforms 3270/CICS screens into modern web interfaces automatically.', 'Generated code follows modern patterns with Angular or React frontends.', 'Business logic conversion maintains transaction integrity and data access patterns.'] }], quiz: [q('What does Blu Age generate from COBOL code?', ['New COBOL code', 'Modern Java or .NET applications', 'Database scripts', 'CloudFormation templates'], 1, 'Blu Age automatically transforms legacy code into modern, maintainable applications.')] },
  { slug: 'microfocus', name: 'Micro Focus Rehosting', description: 'Rehost mainframe applications on AWS with Micro Focus Enterprise Server and COBOL runtime.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Lift-and-Shift Rehosting', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Micro Focus Enterprise Server runs COBOL applications on AWS EC2 instances.', 'JCL scripts are converted to run on Linux or Windows servers.', 'Data access patterns remain unchanged with VSAM file emulation.'] }], quiz: [q('What is the main benefit of Micro Focus rehosting?', ['Complete rewrite', 'Minimal code changes while moving to AWS', 'Free licensing', 'Guaranteed performance improvement'], 1, 'Rehosting moves existing applications to AWS with minimal modifications, reducing migration risk.')] },
  { slug: 'batch_processing', name: 'Batch Processing Modernization', description: 'Migrate JCL batch jobs to Step Functions, Lambda, and managed workflow orchestration.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Modern Batch Workflows', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Step Functions orchestrate batch job sequences with visual workflows.', 'Lambda handles individual batch tasks with auto-scaling and pay-per-use pricing.', 'EventBridge triggers scheduled batch jobs replacing JCL scheduling.'] }], quiz: [q('What AWS service replaces JCL job scheduling?', ['EC2', 'EventBridge', 'S3', 'IAM'], 1, 'EventBridge provides scheduled rule triggers for batch workflows, replacing JCL job scheduling.')] },
  { slug: 'enterprise_modernization', name: 'Enterprise Modernization Strategy', description: 'Design multi-year modernization roadmaps with risk assessment and business value alignment.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Strategic Transformation Planning', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Strangler fig pattern gradually replaces legacy components with new services.', 'Business value assessment prioritizes high-impact, low-risk migrations first.', 'Coexistence strategies allow legacy and modern systems to run in parallel.'] }], quiz: [q('What is the strangler fig pattern?', ['Delete legacy system immediately', 'Gradually replace components while maintaining functionality', 'Build everything new from scratch', 'Keep legacy system forever'], 1, 'The strangler fig pattern incrementally replaces legacy functionality while the system remains operational.')] },
];
