import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Manufacturing',
  slug: 'manufacturing-iot',
  description: 'Transform manufacturing with IoT, digital twins, and predictive maintenance on AWS.',
  orderIndex: 28,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'manufacturing_basics', name: 'Smart Manufacturing Basics', description: 'Understand Industry 4.0 concepts, IoT sensors, and connected factory environments.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Industry 4.0 Revolution', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Smart manufacturing connects factory equipment through IoT sensors and networks.', 'Real-time data collection enables monitoring of production lines and equipment.', 'Cloud analytics transform raw sensor data into actionable manufacturing insights.'] }], quiz: [q('What is the primary goal of smart manufacturing?', ['Reduce workers', 'Connect equipment for real-time monitoring and optimization', 'Replace all machines', 'Eliminate quality control'], 1, 'Smart manufacturing uses IoT and analytics to optimize production efficiency and quality.')] },
  { slug: 'iot_factory', name: 'IoT Factory Floor', description: 'Deploy IoT sensors and gateways for equipment monitoring and data collection.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Industrial IoT Deployment', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT sensors measure temperature, vibration, pressure, and other equipment metrics.', 'Edge gateways aggregate sensor data before sending to cloud for analysis.', 'AWS IoT Greengrass runs local ML inference for real-time equipment monitoring.'] }], quiz: [q('What does AWS IoT Greengrass do?', ['Cloud storage', 'Runs ML inference and Lambda functions at the edge', 'Monitors network traffic', 'Manages user accounts'], 1, 'Greengrass extends AWS Lambda and ML capabilities to factory floor devices for local processing.')] },
  { slug: 'predictive_maintenance', name: 'Predictive Maintenance', description: 'Predict equipment failures before they occur with machine learning models on sensor data.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Anticipating Equipment Failures', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['ML models analyze historical sensor data to predict remaining useful life of components.', 'Anomaly detection identifies unusual patterns indicating potential failures.', 'Maintenance scheduling optimizes downtime windows to minimize production impact.'] }], quiz: [q('What data is most valuable for predictive maintenance?', ['Financial records', 'Historical sensor data and failure records', 'Employee schedules', 'Weather data'], 1, 'Historical sensor readings correlated with actual failures train accurate prediction models.')] },
  { slug: 'digital_twin', name: 'Digital Twin', description: 'Create virtual replicas of physical assets for simulation, analysis, and optimization.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Virtual Asset Replication', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Digital twins mirror physical equipment behavior in real-time cloud models.', 'Simulation tests operational changes without affecting production systems.', 'IoT TwinMaker creates digital twins from existing IoT data and 3D models.'] }], quiz: [q('What is a digital twin?', ['A backup copy', 'A virtual replica of a physical asset that mirrors its behavior', 'A 3D model only', 'A database schema'], 1, 'Digital twins provide real-time virtual representations of physical assets for analysis and optimization.')] },
  { slug: 'quality_control', name: 'AI Quality Control', description: 'Automate quality inspection with computer vision and anomaly detection systems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Automated Visual Inspection', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Computer vision models detect defects in manufactured products automatically.', 'Rekognition analyzes images from production line cameras in real-time.', 'Edge inference processes images locally for immediate quality decisions.'] }], quiz: [q('How does computer vision improve quality control?', ['Replaces workers', 'Automates defect detection with consistent accuracy', 'Reduces production speed', 'Eliminates testing'], 1, 'Computer vision provides consistent, objective quality inspection without human fatigue or bias.')] },
  { slug: 'manufacturing_enterprise', name: 'Manufacturing Enterprise', description: 'Integrate manufacturing systems with ERP, supply chain, and business intelligence platforms.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Connected Enterprise Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['MES integration connects shop floor systems with enterprise resource planning.', 'Supply chain visibility tracks materials from suppliers through production.', 'Business intelligence dashboards provide real-time manufacturing KPI monitoring.'] }], quiz: [q('What does MES stand for in manufacturing?', ['Manufacturing Execution System', 'Machine Event Service', 'Managed Equipment Storage', 'Memory Encryption Standard'], 0, 'MES manages and monitors work-in-progress on the factory floor from order to finished goods.')] },
];
