import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Media & Entertainment',
  slug: 'media-streaming',
  description: 'Build streaming platforms, game servers, and content delivery solutions for entertainment.',
  orderIndex: 31,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'streaming_basics', name: 'Streaming Platform Basics', description: 'Understand OTT architecture, adaptive bitrate streaming, and content delivery for video platforms.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Video Streaming Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['OTT platforms deliver video directly to viewers over the internet.', 'Adaptive bitrate streaming adjusts quality based on viewer bandwidth.', 'CDN distribution caches content at edge locations for low-latency delivery.'] }], quiz: [q('What is adaptive bitrate streaming?', ['Fixed quality video', 'Adjusts video quality based on viewer bandwidth', 'Audio only streaming', 'Live broadcasting'], 1, 'Adaptive streaming provides the best possible quality for each viewer\'s network conditions.')] },
  { slug: 'content_delivery', name: 'Content Delivery', description: 'Distribute video globally with CloudFront, MediaPackage, and multi-CDN strategies.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Global Content Distribution', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CloudFront caches video content at over 400 edge locations worldwide.', 'Origin Shield provides an additional caching layer to reduce origin load.', 'Multi-CDN strategies use multiple providers for redundancy and performance.'] }], quiz: [q('What is CloudFront Origin Shield?', ['First origin server', 'Additional caching layer to reduce origin load and costs', 'Security firewall', 'Load balancer'], 1, 'Origin Shield sits between your origin and edge locations, reducing repeated origin fetches.')] },
  { slug: 'game_servers', name: 'Game Server Hosting', description: 'Deploy and scale multiplayer game servers with GameLift for real-time gameplay.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Multiplayer Game Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GameLift hosts dedicated game servers with automatic scaling and player matching.', 'FleetIQ optimizes EC2 Spot Instances for cost-effective game server hosting.', 'Real-time multiplayer requires low-latency connections and state synchronization.'] }], quiz: [q('What does Amazon GameLift provide?', ['Game development tools', 'Dedicated game server hosting with auto-scaling', 'Game streaming', 'Game analytics only'], 1, 'GameLift manages dedicated game servers with automatic scaling and player matchmaking.')] },
  { slug: 'live_broadcasting', name: 'Live Broadcasting', description: 'Stream live events with multi-bitrate encoding, DVR capabilities, and global reach.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Live Event Production', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['MediaLive encodes live video into multiple bitrates simultaneously.', 'Time-shifted viewing lets audiences pause, rewind, and restart live content.', 'Redundant input feeds ensure uninterrupted live broadcasts.'] }], quiz: [q('How does time-shifted viewing work?', ['Records to tape', 'Buffers live content allowing pause and rewind', 'Delays broadcast by hours', 'Only works on TV'], 1, 'Time-shifted viewing stores recent live content allowing viewers to control their watching experience.')] },
  { slug: 'vfx_cloud', name: 'VFX & Rendering', description: 'Accelerate visual effects and animation rendering with scalable cloud compute resources.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Cloud Rendering Farm', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Burst rendering scales compute for tight production deadlines.', 'High-performance storage like FSx for Lustre provides parallel file system access.', 'Deadline Cloud manages render queues and distributes work across compute fleets.'] }], quiz: [q('What is burst rendering?', ['Render at normal speed', 'Scale up compute temporarily for tight deadlines', 'Render only at night', 'Use single powerful machine'], 1, 'Burst rendering temporarily adds massive compute capacity to meet critical production deadlines.')] },
  { slug: 'entertainment_ai', name: 'Entertainment AI', description: 'Apply machine learning to content recommendation, personalization, and audience analytics.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Intelligent Entertainment', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Personalization engines recommend content based on viewing history and preferences.', 'Computer vision analyzes video content for automatic tagging and moderation.', 'Audience analytics predict churn and optimize content investment decisions.'] }], quiz: [q('How do streaming platforms reduce subscriber churn?', ['Lower prices only', 'Content recommendation and personalization', 'Remove content', 'Increase ads'], 1, 'Personalized recommendations keep viewers engaged by surfacing relevant content they enjoy.')] },
];
