import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Media Services',
  slug: 'media-services',
  description: 'Process, store, and deliver video and audio content with broadcast and OTT solutions.',
  orderIndex: 20,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'mediaconvert', name: 'AWS Elemental MediaConvert', description: 'Transcode video files into broadcast-quality formats for streaming and delivery.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'File-Based Video Transcoding', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['MediaConvert converts video from broadcast sources into OTT streaming formats.', 'Output presets optimize files for delivery to TVs, PCs, and mobile devices.', 'Job templates define reusable transcoding configurations for consistent output.'] }], quiz: [q('What is the primary purpose of MediaConvert?', ['Live video streaming', 'File-based video transcoding for multiple delivery formats', 'Video conferencing', 'Image processing'], 1, 'MediaConvert transforms video files into formats optimized for streaming to various devices.')] },
  { slug: 'medialive', name: 'AWS Elemental MediaLive', description: 'Create live video streams for broadcast and OTT delivery with real-time processing.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Live Video Processing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['MediaLive processes live video streams for broadcast and web delivery.', 'Input sources include RTMP, HLS, and SDI from professional encoders.', 'Output channels create adaptive bitrate streams for multiple devices.'] }], quiz: [q('What input types does MediaLive support?', ['Only RTMP', 'RTMP, HLS, SDI, and other broadcast standards', 'Only HTTP', 'Only file uploads'], 1, 'MediaLive accepts various live input formats including RTMP, HLS, and professional SDI connections.')] },
  { slug: 'mediapackage', name: 'AWS Elemental MediaPackage', description: 'Prepare and protect live video streams with just-in-time packaging and DRM.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Just-in-Time Packaging', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['MediaPackage converts live streams into formats suitable for multiple playback devices.', 'DRM integration protects content with Widevine and FairPlay encryption.', 'Time-shifted viewing allows audiences to pause and rewind live content.'] }], quiz: [q('What does just-in-time packaging mean?', ['Package content before upload', 'Package content on-demand for each viewer request', 'Pre-package for all devices', 'Package during encoding'], 1, 'MediaPackage creates optimized streams on-demand for each viewer device and format requirement.')] },
  { slug: 'mediaconnect', name: 'AWS Elemental MediaConnect', description: 'Transport live video over the internet with reliable, secure contribution feeds.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Live Video Transport', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['MediaConnect transports live video feeds over public internet connections.', 'Failover mechanisms automatically switch to backup streams if primary fails.', 'Encryption and authentication secure video feeds during transport.'] }], quiz: [q('How does MediaConnect handle transport failures?', ['Stops the stream', 'Automatic failover to backup streams', 'Requires manual restart', 'Ignores errors'], 1, 'MediaConnect provides automatic failover to ensure continuous video delivery even with network issues.')] },
  { slug: 'ott_architecture', name: 'OTT Architecture', description: 'Build end-to-end over-the-top streaming platforms with content management and delivery.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Streaming Platform Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['OTT platforms combine ingest, processing, packaging, and delivery components.', 'Content management systems organize metadata, thumbnails, and programming schedules.', 'CDN integration distributes streams globally with low-latency delivery.'] }], quiz: [q('What does OTT stand for?', ['Over The Top', 'Online Television Transport', 'Optimized Transmission Technology', 'Open Television Standard'], 0, 'OTT delivers content directly to viewers over the internet, bypassing traditional broadcast infrastructure.')] },
  { slug: 'media_ai', name: 'Media AI Services', description: 'Automate video analysis, content moderation, and metadata generation with machine learning.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Intelligent Media Processing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Rekognition Video analyzes live and stored video for objects, faces, and activities.', 'Transcribe converts speech to text for subtitles and content search.', 'Comprehend extracts sentiment and entities from video transcripts.'] }], quiz: [q('Which AWS service transcribes speech from video content?', ['Rekognition', 'Transcribe', 'Comprehend', 'Polly'], 1, 'Amazon Transcribe converts spoken audio from video into accurate text for captions and analysis.')] },
];
