import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Mixed Reality',
  slug: 'mixed-reality',
  description: 'Build AR/VR experiences with Sumerian, managed rendering, and spatial computing on AWS.',
  orderIndex: 49,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'xr_basics', name: 'XR Fundamentals', description: 'Understand augmented, virtual, and mixed reality technologies and use cases.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Extended Reality Spectrum', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Augmented reality overlays digital content on the real world.', 'Virtual reality creates fully immersive digital environments.', 'Mixed reality blends physical and digital worlds with interaction.'] }], quiz: [q('What is the difference between AR and VR?', ['Same thing', 'AR overlays on reality, VR creates fully immersive environments', 'VR is cheaper', 'AR requires headsets'], 1, 'AR enhances the real world with digital overlays while VR replaces the real world entirely.')] },
  { slug: 'sumerian', name: 'Amazon Sumerian', description: 'Create 3D VR and AR scenes with a web-based editor and JavaScript APIs.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Web-Based 3D Authoring', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Sumerian provides a browser-based editor for creating 3D scenes.', 'Hosts are interactive 3D characters with natural language capabilities.', 'Scenes export to web browsers for cross-platform AR/VR experiences.'] }], quiz: [q('What is Amazon Sumerian?', ['VR headset', 'Web-based 3D scene editor for AR/VR experiences', 'Game engine', '3D printer software'], 1, 'Sumerian is a browser-based tool for creating immersive 3D experiences without deep coding.')] },
  { slug: 'cloud_rendering', name: 'Cloud Rendering', description: 'Render high-quality graphics remotely for lightweight AR/VR client devices.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Remote Graphics Processing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Cloud rendering streams high-quality graphics to lightweight devices.', 'Low-latency video streaming enables responsive VR interactions.', 'GPU instances provide scalable rendering capacity for multiple users.'] }], quiz: [q('Why use cloud rendering for VR?', ['Faster internet only', 'Enables high-quality graphics on lightweight devices', 'Cheaper headsets', 'Simpler development'], 1, 'Cloud rendering offloads graphics processing to powerful servers, allowing lighter, cheaper headsets.')] },
  { slug: 'spatial_computing', name: 'Spatial Computing', description: 'Build applications that understand and interact with physical space using AR frameworks.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Understanding Physical Space', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Spatial anchors pin digital content to real-world locations.', 'Plane detection identifies surfaces for placing virtual objects.', 'Environment mapping creates 3D meshes of physical spaces.'] }], quiz: [q('What is a spatial anchor?', ['GPS location', 'A point that pins digital content to a real-world location', 'A security key', 'A database index'], 1, 'Spatial anchors maintain the position of virtual objects relative to the physical world.')] },
  { slug: 'xr_ai', name: 'XR AI', description: 'Apply machine learning to object recognition, hand tracking, and spatial understanding for XR.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Enhanced XR', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Object recognition identifies real-world objects for AR interactions.', 'Hand tracking enables natural gesture input without controllers.', 'Scene understanding builds semantic maps of physical environments.'] }], quiz: [q('How does AI improve XR experiences?', ['Faster graphics only', 'Enables natural interaction through object and gesture recognition', 'Reduces cost only', 'Simplifies development only'], 1, 'AI adds intelligence to XR by understanding environments and enabling natural user interaction.')] },
  { slug: 'xr_enterprise', name: 'XR Enterprise', description: 'Deploy enterprise AR/VR solutions for training, remote assistance, and visualization.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise XR Solutions', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AR remote assistance overlays expert guidance on field technician views.', 'VR training provides safe, repeatable practice for dangerous procedures.', '3D visualization enables collaborative design review across locations.'] }], quiz: [q('What is AR remote assistance?', ['Phone support only', 'Overlaying expert guidance on technician views in real-time', 'Email documentation', 'Video conferencing only'], 1, 'AR remote assistance lets experts see what field workers see and provide visual guidance overlay.')] },
];
