import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Network Security',
  slug: 'network-security',
  description: 'Protect network infrastructure with firewalls, DDoS protection, and traffic inspection on AWS.',
  orderIndex: 16,
  theme: 'CITADEL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'shield_basics', name: 'AWS Shield Basics', description: 'Protect applications from DDoS attacks with managed threat detection and mitigation.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'DDoS Protection', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Shield Standard provides automatic protection against common Layer 3 and Layer 4 attacks.', 'Shield Advanced offers 24/7 DDoS Response Team access and cost protection.', 'Shield integrates with CloudFront, Route 53, ELB, and Global Accelerator.'] }], quiz: [q('Which Shield tier provides access to a 24/7 DDoS Response Team?', ['Shield Standard', 'Shield Advanced', 'Both', 'Neither'], 1, 'Shield Advanced includes DRT access for customized mitigations during sophisticated DDoS attacks.')] },
  { slug: 'network_firewall', name: 'AWS Network Firewall', description: 'Deploy managed firewall rules to protect VPC traffic with intrusion detection and prevention.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Managed Network Firewall', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Network Firewall filters traffic at the VPC boundary with stateful and stateless rules.', 'Suricata-compatible intrusion detection and prevention rules inspect packet content.', 'Firewall managed rule groups provide pre-configured protections for common threats.'] }], quiz: [q('What inspection engine does AWS Network Firewall use?', ['iptables', 'Suricata', 'Snort', 'pfSense'], 1, 'Network Firewall uses Suricata, an open-source intrusion detection and prevention engine.')] },
  { slug: 'vpc_flow_logs', name: 'VPC Flow Logs', description: 'Capture and analyze network traffic metadata for security monitoring and troubleshooting.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Network Traffic Monitoring', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['VPC Flow Logs capture information about IP traffic going to and from network interfaces.', 'Flow log data can be published to CloudWatch Logs, S3, or Kinesis Data Firehose.', 'Traffic analytics with Athena and QuickSight enable deep network forensics.'] }], quiz: [q('Where can VPC Flow Log data be sent for analysis?', ['Only to CloudWatch Logs', 'CloudWatch Logs, S3, or Kinesis Data Firehose', 'Only to S3', 'Only to CloudTrail'], 1, 'Flow logs support three destinations: CloudWatch Logs for real-time analysis, S3 for long-term storage, and Kinesis for streaming analytics.')] },
  { slug: 'waf_advanced', name: 'AWS WAF Advanced', description: 'Build sophisticated web application firewall rules with rate limiting, bot control, and managed rules.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Advanced Web Protection', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Rate-based rules throttle requests from IPs exceeding defined thresholds.', 'AWS Managed Rules provide pre-configured rule groups for OWASP Top 10 and common threats.', 'Bot Control identifies and manages automated bot traffic separately from human users.'] }], quiz: [q('Which WAF feature automatically blocks IPs exceeding a request threshold?', ['IP Set matching', 'Rate-based rules', 'Geographic matching', 'SQL injection protection'], 1, 'Rate-based rules count requests per IP and block those exceeding the defined rate threshold.')] },
  { slug: 'security_architecture', name: 'Network Security Architecture', description: 'Design defense-in-depth network architectures with layered security controls and zero trust.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Defense in Depth', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Zero trust architecture verifies every request regardless of network location.', 'Micro-segmentation with security groups limits lateral movement within VPCs.', 'PrivateLink provides private connectivity to services without public internet exposure.'] }], quiz: [q('What is the core principle of zero trust network architecture?', ['Trust all internal traffic', 'Verify every request regardless of network location', 'Use firewall only at the perimeter', 'Allow all outbound traffic'], 1, 'Zero trust assumes no implicit trust and requires verification for every connection, whether internal or external.')] },
  { slug: 'ddos_response', name: 'DDoS Response Planning', description: 'Develop incident response playbooks and automated mitigations for DDoS attack scenarios.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'DDoS Incident Response', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Shield Advanced cost protection reimburses scaling charges during DDoS events.', 'Automated Shield Advanced mitigations activate within minutes of detection.', 'Runbooks define step-by-step procedures for manual intervention during attacks.'] }], quiz: [q('What does Shield Advanced cost protection provide?', ['Free EC2 instances', 'Reimbursement of scaling costs incurred during DDoS attacks', 'Free data transfer', 'Free WAF rules'], 1, 'Shield Advanced reimburses Elastic Load Balancing and Auto Scaling costs incurred as a result of DDoS attacks.')] },
];
