import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Nonprofit & Education',
  slug: 'nonprofit-programs',
  description: 'Leverage AWS programs for nonprofits, schools, and research institutions with discounted cloud services.',
  orderIndex: 34,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'nonprofit_basics', name: 'Nonprofit Cloud Basics', description: 'Understand AWS credits, discounts, and programs available for charitable organizations.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'AWS for Nonprofits', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS Activate provides credits and support for eligible nonprofit organizations.', 'Discounted pricing reduces cloud costs for mission-driven organizations.', 'Grant programs fund technology projects that advance social impact goals.'] }], quiz: [q('What does AWS Activate provide for nonprofits?', ['Free hardware', 'Cloud credits and technical support', 'Office space', 'Legal services'], 1, 'AWS Activate offers cloud credits and guidance to help nonprofits adopt cloud technology.')] },
  { slug: 'education_cloud', name: 'Education Cloud', description: 'Deploy learning management systems, student portals, and research computing on AWS.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Academic Technology', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['LMS platforms like Moodle and Canvas run reliably on AWS infrastructure.', 'Student information systems manage enrollment, grades, and campus services.', 'Research computing provides HPC resources for academic research projects.'] }], quiz: [q('What is the primary benefit of LMS on AWS?', ['Cheaper software', 'Scalable infrastructure for peak enrollment periods', 'Faster internet', 'Better textbooks'], 1, 'AWS provides elastic scaling to handle enrollment spikes and research compute demands.')] },
  { slug: 'research_computing', name: 'Research Computing', description: 'Provide HPC clusters, data analytics, and machine learning for scientific research.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Academic HPC on AWS', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Parallel computing clusters process large scientific datasets efficiently.', 'Machine learning accelerates research in genomics, climate science, and physics.', 'Data lakes store petabytes of research data with cost-effective storage tiers.'] }], quiz: [q('Why is cloud HPC valuable for research?', ['Cheaper computers', 'Elastic scaling for compute-intensive research workloads', 'Faster internet', 'Simpler software'], 1, 'Cloud HPC provides massive compute resources on-demand without permanent infrastructure investment.')] },
  { slug: 'student_analytics', name: 'Student Analytics', description: 'Analyze student engagement, predict at-risk learners, and personalize educational experiences.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Learning Analytics', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Early alert systems identify students at risk of dropping courses.', 'Engagement tracking measures participation in online learning activities.', 'Personalized learning paths adapt content to individual student needs.'] }], quiz: [q('How can analytics help reduce student dropout rates?', ['By reducing workload', 'Early identification of at-risk students for intervention', 'By making courses easier', 'By reducing costs'], 1, 'Analytics identify struggling students early so institutions can provide targeted support.')] },
  { slug: 'digital_access', name: 'Digital Access', description: 'Bridge the digital divide with accessible, affordable technology solutions for underserved communities.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Technology for All', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Low-bandwidth solutions provide access in areas with limited internet connectivity.', 'Offline-first applications work without constant connectivity.', 'Assistive technologies ensure accessibility for users with disabilities.'] }], quiz: [q('What is offline-first design?', ['Requires constant internet', 'Applications that work without connectivity and sync later', 'Cloud-only architecture', 'Mobile-only design'], 1, 'Offline-first applications maintain functionality without internet access, syncing data when connectivity returns.')] },
  { slug: 'nonprofit_enterprise', name: 'Nonprofit Enterprise', description: 'Scale nonprofit operations with donor management, volunteer coordination, and impact measurement.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Impact Technology', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['CRM systems manage donor relationships and fundraising campaigns.', 'Volunteer management platforms coordinate volunteer activities and scheduling.', 'Impact measurement tools quantify program outcomes for stakeholder reporting.'] }], quiz: [q('What technology helps nonprofits demonstrate impact?', ['Social media', 'Data analytics and impact measurement tools', 'Website only', 'Email marketing'], 1, 'Analytics platforms measure and report on program outcomes to demonstrate effectiveness to stakeholders.')] },
];
