import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Professional Services',
  slug: 'professional-services',
  description: 'Deliver consulting, managed operations, and technology services with cloud-based platforms.',
  orderIndex: 44,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'consulting_cloud', name: 'Cloud Consulting', description: 'Provide cloud architecture assessments, migration planning, and optimization services.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Cloud Advisory Services', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Well-Architected reviews assess workloads against AWS best practices.', 'Migration assessments evaluate application readiness for cloud deployment.', 'Cost optimization identifies opportunities to reduce cloud spending.'] }], quiz: [q('What is a Well-Architected review?', ['Code audit', 'Assessment of workloads against AWS best practices', 'Security scan', 'Performance test'], 1, 'Well-Architected reviews evaluate architectures across operational excellence, security, reliability, performance, and cost.')] },
  { slug: 'managed_operations', name: 'Managed Operations', description: 'Provide ongoing monitoring, patching, and support for customer cloud environments.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Managed Cloud Services', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['24/7 monitoring detects and responds to operational issues.', 'Patch management keeps systems updated with security fixes.', 'Incident response provides escalation and resolution for cloud events.'] }], quiz: [q('What does managed operations include?', ['Development only', 'Monitoring, patching, and incident response', 'Marketing', 'Sales only'], 1, 'Managed operations provide ongoing operational support for cloud infrastructure and applications.')] },
  { slug: 'project_delivery', name: 'Project Delivery', description: 'Manage cloud projects with agile methodologies, stakeholder communication, and quality assurance.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Cloud Project Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Agile sprints deliver cloud increments with regular stakeholder feedback.', 'Risk management identifies and mitigates project delivery risks.', 'Quality gates ensure deliverables meet acceptance criteria before deployment.'] }], quiz: [q('Why use agile for cloud projects?', ['Faster coding only', 'Regular feedback and incremental delivery reduce project risk', 'Lower costs', 'Simpler architecture'], 1, 'Agile methodologies provide regular checkpoints to ensure projects stay aligned with business goals.')] },
  { slug: 'service_catalog', name: 'Service Catalog', description: 'Create standardized cloud services and offerings for consistent delivery and governance.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Standardized Service Delivery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Service catalogs provide pre-approved cloud architectures for common use cases.', 'Governance controls enforce standards and compliance automatically.', 'Self-service portals enable customers to deploy approved services.'] }], quiz: [q('What is a cloud service catalog?', ['Product list', 'Collection of pre-approved cloud architectures for self-service deployment', 'Documentation', 'Training materials'], 1, 'Service catalogs provide standardized, governed cloud offerings that customers can deploy independently.')] },
  { slug: 'professional_ai', name: 'Professional Services AI', description: 'Apply machine learning to service delivery automation, knowledge management, and client analytics.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Enhanced Services', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Automation reduces manual tasks in cloud operations and service delivery.', 'Knowledge management systems capture and share expertise across teams.', 'Client analytics provide insights into usage patterns and optimization opportunities.'] }], quiz: [q('How does AI improve professional services?', ['Replaces consultants', 'Automates routine tasks and provides data-driven insights', 'Reduces quality', 'Eliminates training'], 1, 'AI enhances service delivery by automating repetitive work and providing analytical insights.')] },
  { slug: 'service_enterprise', name: 'Service Enterprise', description: 'Scale professional services with talent management, IP development, and global delivery models.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Global Services Organization', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Talent management systems track skills and certifications across teams.', 'IP development creates reusable accelerators and solution patterns.', 'Global delivery leverages distributed teams for 24/7 service capabilities.'] }], quiz: [q('What is IP development in professional services?', ['Intellectual property creation', 'Building reusable accelerators and solution patterns', 'Hardware development', 'Software licensing'], 1, 'IP development creates reusable components and patterns that accelerate future client engagements.')] },
];
