import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Python for Cloud',
  slug: 'python-for-cloud',
  description: 'Build serverless applications, automate AWS tasks, and develop cloud-native services with Python.',
  orderIndex: 14,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'python_basics', name: 'Python Basics', description: 'Learn core Python syntax, data structures, and functions for cloud development.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Python Fundamentals', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Python uses dynamic typing and an interpreted execution model for rapid development.', 'Lists, dictionaries, and sets are the primary data structures for cloud scripting.', 'Functions with default arguments and keyword arguments enable flexible API designs.'] }], quiz: [q('Which data structure is best for key-value lookups in Python?', ['List', 'Tuple', 'Dictionary', 'Set'], 2, 'Dictionaries provide O(1) average-case lookup by key, making them ideal for mapping data.')] },
  { slug: 'boto3_fundamentals', name: 'Boto3 Fundamentals', description: 'Interact with AWS services programmatically using the official Python SDK.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'AWS SDK for Python', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Boto3 is the official Python SDK for interacting with AWS services.', 'Resources provide high-level object-oriented interfaces for service operations.', 'Clients provide low-level access to AWS service API operations.'] }], quiz: [q('What is the difference between Boto3 resources and clients?', ['Resources are faster', 'Resources are high-level object-oriented; clients are low-level API calls', 'Clients are deprecated', 'There is no difference'], 1, 'Resources abstract service interactions into objects, while clients provide direct access to API methods.')] },
  { slug: 'lambda_python', name: 'Lambda with Python', description: 'Build and deploy serverless Python functions with Lambda, API Gateway, and DynamoDB.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Serverless Python', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Lambda functions written in Python handle HTTP requests, events, and scheduled tasks.', 'Lambda layers share common dependencies across multiple functions.', 'The handler function receives event and context objects as parameters.'] }], quiz: [q('What does the Lambda handler function receive as input?', ['Only the event data', 'Event data and a context object', 'A database connection', 'An IAM role'], 1, 'The handler receives an event dict containing the trigger data and a context object with runtime information.')] },
  { slug: 'aws_lambda_power', name: 'Python AWS Automation', description: 'Automate cloud operations, resource management, and reporting with Python scripts and Boto3.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Operational Automation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Python scripts can automate instance lifecycle, snapshot management, and cost reporting.', 'CloudWatch Logs Insights queries can be automated for daily operational reports.', 'EventBridge scheduled rules can trigger Lambda functions for routine maintenance tasks.'] }], quiz: [q('Which AWS service triggers Python Lambda functions on a schedule?', ['SNS', 'EventBridge', 'SQS', 'S3'], 1, 'EventBridge scheduled rules invoke Lambda functions on cron or rate expressions for automated tasks.')] },
  { slug: 'python_testing', name: 'Python Testing & Packaging', description: 'Write unit tests, mock AWS services, and package Python Lambda functions with layers.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Testing and Packaging', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['moto library mocks AWS services for local unit testing without real API calls.', 'pytest with fixtures provides a clean testing framework for Lambda functions.', 'Lambda layers package shared dependencies separately to reduce deployment package size.'] }], quiz: [q('What Python library mocks AWS services for local testing?', ['unittest', 'moto', 'boto3', 'pytest'], 1, 'moto provides lightweight mock implementations of AWS services for testing without making real API calls.')] },
  { slug: 'python_architecture', name: 'Python Cloud Architecture', description: 'Design production Python applications with async processing, connection pooling, and structured logging.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Production Patterns', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AsyncIO enables concurrent API calls and database queries without threading overhead.', 'Connection pooling with RDS Proxy reduces database connection overhead for Lambda.', 'Structured JSON logging with structlog enables automated log analysis with CloudWatch.'] }], quiz: [q('What is the benefit of connection pooling for Python Lambda functions?', ['Faster cold starts', 'Reduces database connection overhead by reusing connections', 'Increases memory allocation', 'Enables auto-scaling'], 1, 'Connection pooling reuses database connections across Lambda invocations, avoiding the overhead of establishing new connections.')] },
];
