import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Quantum Computing',
  slug: 'quantum-braket',
  description: 'Explore quantum computing with Amazon Braket for quantum algorithm development and research.',
  orderIndex: 23,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'quantum_basics', name: 'Quantum Computing Basics', description: 'Understand qubits, superposition, entanglement, and quantum gates fundamentals.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Quantum Mechanics for Computing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Qubits can exist in superposition of both 0 and 1 states simultaneously.', 'Entanglement links qubits so the state of one instantly affects the other.', 'Quantum gates manipulate qubits using rotation and phase operations.'] }], quiz: [q('What is superposition in quantum computing?', ['A qubit is always 0', 'A qubit can be in multiple states simultaneously', 'Qubits are duplicated', 'Measurement is instant'], 1, 'Superposition allows qubits to represent multiple values at once, enabling parallel computation.')] },
  { slug: 'braket_basics', name: 'Amazon Braket Basics', description: 'Access quantum hardware and simulators through the fully managed quantum computing service.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Quantum Computing Service', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Braket provides access to quantum computers from IonQ, QuEra, and Rigetti.', 'Simulators allow testing quantum circuits before running on real hardware.', 'Tasks run asynchronously with results stored in S3 for later retrieval.'] }], quiz: [q('What types of quantum hardware does Braket support?', ['Only simulators', 'Superconducting, trapped ion, and annealing devices', 'Only IBM Q', 'Only D-Wave'], 1, 'Braket provides access to multiple quantum technologies from different hardware providers.')] },
  { slug: 'quantum_circuits', name: 'Quantum Circuit Design', description: 'Build quantum circuits with gates, measurements, and hybrid classical-quantum algorithms.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Circuit-Based Quantum Computing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Quantum circuits apply sequences of gates to qubits before measurement.', 'Variational algorithms use classical optimization with quantum circuit evaluation.', 'Noise models simulate real hardware imperfections for realistic testing.'] }], quiz: [q('What is a variational quantum algorithm?', ['Purely quantum algorithm', 'Hybrid classical-quantum approach using parameterized circuits', 'Classical algorithm only', 'Quantum annealing only'], 1, 'Variational algorithms use classical computers to optimize parameters in quantum circuits.')] },
  { slug: 'quantum_algorithms', name: 'Quantum Algorithms', description: 'Implement Shor\'s algorithm, Grover\'s search, and quantum machine learning models.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Quantum Algorithm Library', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Shor\'s algorithm factors large numbers exponentially faster than classical methods.', 'Grover\'s search provides quadratic speedup for unstructured database searches.', 'Quantum machine learning explores quantum kernels and variational classifiers.'] }], quiz: [q('What advantage does Grover\'s algorithm provide?', ['Exponential speedup', 'Quadratic speedup for searching unstructured data', 'No advantage', 'Faster than classical for all problems'], 1, 'Grover\'s algorithm searches unstructured data quadratically faster than classical algorithms.')] },
  { slug: 'quantum_error_correction', name: 'Quantum Error Correction', description: 'Protect quantum information from noise and decoherence with error correction codes.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Protecting Quantum Information', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Quantum error correction encodes logical qubits across multiple physical qubits.', 'Surface codes are leading candidates for fault-tolerant quantum computing.', 'Error thresholds define the maximum noise level for reliable quantum computation.'] }], quiz: [q('Why is quantum error correction necessary?', ['Qubits are cheap', 'Physical qubits are susceptible to noise and decoherence', 'Increases speed', 'Reduces cost'], 1, 'Error correction protects fragile quantum states from environmental noise and computation errors.')] },
  { slug: 'quantum_applications', name: 'Quantum Applications', description: 'Apply quantum computing to optimization, chemistry simulation, and cryptography problems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Real-World Quantum Use Cases', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Quantum optimization tackles logistics, portfolio optimization, and scheduling problems.', 'Quantum chemistry simulates molecular interactions for drug discovery and materials science.', 'Post-quantum cryptography develops algorithms resistant to quantum computer attacks.'] }], quiz: [q('Which industry benefits from quantum chemistry simulation?', ['Retail', 'Pharmaceuticals and materials science', 'Transportation', 'Hospitality'], 1, 'Quantum computers can simulate molecular behavior for drug discovery and new material development.')] },
];
