import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Real-Time Analytics',
  slug: 'real-time-analytics',
  description: 'Process and analyze streaming data in real time with Kinesis, Managed Streaming for Kafka, and OpenSearch.',
  orderIndex: 17,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'kinesis_basics', name: 'Kinesis Data Streams', description: 'Collect and process large streams of data records in real time with managed streaming.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Streaming Data Ingestion', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Kinesis Data Streams captures and stores data records from multiple sources.', 'Shards define the throughput capacity — each shard supports 1 MB/s in and 2 MB/s out.', 'Enhanced fan-out provides dedicated throughput per consumer for low-latency processing.'] }], quiz: [q('What unit of capacity does Kinesis Data Streams use?', ['Instance', 'Shard', 'Partition', 'Replica'], 1, 'Shards define the throughput capacity of a Kinesis stream with specific read/write limits.')] },
  { slug: 'kinesis_firehose', name: 'Kinesis Data Firehose', description: 'Load streaming data into S3, Redshift, OpenSearch, or HTTP endpoints automatically.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Stream Loading', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Firehose automatically delivers streaming data to configured destinations.', 'Built-in data transformation converts record formats before delivery.', 'Batching buffers records to optimize delivery frequency and cost.'] }], quiz: [q('Which feature of Firehose converts data formats before delivery?', ['Lambda transformation', 'Data Analytics', 'CloudWatch Logs', 'Glue ETL'], 0, 'Firehose can invoke Lambda functions to transform, compress, or encrypt records before delivery.')] },
  { slug: 'kinesis_analytics', name: 'Kinesis Data Analytics', description: 'Run SQL queries and Apache Flink applications on streaming data in real time.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Stream Processing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Kinesis Data Analytics runs SQL queries against streaming data from Kinesis or Firehose.', 'Apache Flink support enables complex event processing with Java or Python.', 'Window functions aggregate streaming data over time intervals for insights.'] }], quiz: [q('Which programming model does Flink use for stream processing?', ['MapReduce', 'Micro-batch', 'Event-time processing with windows', 'Request-response'], 2, 'Flink processes events as they arrive using event-time semantics and configurable window types.')] },
  { slug: 'opensearch', name: 'Amazon OpenSearch', description: 'Search, analyze, and visualize log data with a managed Elasticsearch-compatible service.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Search and Analytics', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['OpenSearch is a managed service for Elasticsearch-compatible search and analytics.', 'OpenSearch Dashboards provides visualization and monitoring dashboards.', 'Index policies automate lifecycle management for log data rotation and deletion.'] }], quiz: [q('What is OpenSearch Dashboards used for?', ['Database management', 'Visualization and monitoring of indexed data', 'Container orchestration', 'Code deployment'], 1, 'OpenSearch Dashboards provides interactive visualizations, dashboards, and monitoring for data indexed in OpenSearch.')] },
  { slug: 'streaming_architecture', name: 'Streaming Architecture', description: 'Design production streaming architectures with exactly-once processing and schema evolution.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Production Streaming Patterns', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Exactly-once processing ensures each record is processed one time despite retries.', 'Schema Registry manages data schemas for evolving streaming applications.', 'Dead letter queues capture failed records for reprocessing without blocking the stream.'] }], quiz: [q('What problem do dead letter queues solve in streaming architectures?', ['Increase throughput', 'Capture failed records for reprocessing without blocking the main stream', 'Encrypt data in transit', 'Reduce storage costs'], 1, 'DLQs isolate problematic records so the main stream continues processing while failures are investigated.')] },
  { slug: 'real_time_ml', name: 'Real-Time ML Inference', description: 'Deploy machine learning models for real-time inference on streaming data with low latency.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Streaming ML Predictions', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['SageMaker Real-Time Endpoints serve model predictions with single-digit millisecond latency.', 'Kinesis Data Analytics can invoke SageMaker endpoints for real-time scoring.', 'Feature Store provides consistent feature values for both training and real-time inference.'] }], quiz: [q('Which service provides low-latency model predictions for streaming data?', ['SageMaker Batch Transform', 'SageMaker Real-Time Endpoints', 'SageMaker Ground Truth', 'SageMaker Canvas'], 1, 'SageMaker Real-Time Endpoints host models for online serving with consistent low-latency predictions.')] },
];
