import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Real Estate Technology',
  slug: 'real-estate-tech',
  description: 'Modernize property management with smart buildings, IoT, and digital transaction platforms.',
  orderIndex: 38,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'smart_building', name: 'Smart Building Basics', description: 'Understand IoT sensors, building automation, and intelligent facility management systems.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Intelligent Building Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['IoT sensors monitor occupancy, temperature, air quality, and energy usage.', 'Building automation systems control HVAC, lighting, and security automatically.', 'Predictive maintenance prevents equipment failures through sensor monitoring.'] }], quiz: [q('What is the primary benefit of smart building IoT?', ['Faster internet', 'Automated optimization of energy and occupant comfort', 'Cheaper construction', 'Better外观'], 1, 'Smart buildings reduce energy costs while improving occupant comfort through automated controls.')] },
  { slug: 'property_management', name: 'Property Management', description: 'Deploy cloud-based property management with tenant portals and maintenance tracking.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Digital Property Operations', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Tenant portals provide online rent payment and maintenance request submission.', 'Lease management tracks expirations, renewals, and rent escalations.', 'Maintenance tracking coordinates work orders with vendors and contractors.'] }], quiz: [q('What does tenant portal software provide?', ['Only rent collection', 'Online access to payments, maintenance, and lease information', 'Marketing only', 'Construction management'], 1, 'Tenant portals centralize communication, payments, and service requests for better tenant experience.')] },
  { slug: 'virtual_tours', name: 'Virtual Property Tours', description: 'Create immersive 3D property tours with virtual reality and interactive floor plans.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Immersive Property Marketing', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['3D scanning creates photorealistic models of properties for virtual walkthroughs.', 'VR experiences let remote buyers explore properties immersively.', 'Interactive floor plans provide spatial understanding with measurement tools.'] }], quiz: [q('What technology enables remote property walkthroughs?', ['2D photos only', '3D scanning and virtual reality', 'Paper floor plans', 'Phone calls'], 1, '3D scanning and VR create immersive experiences allowing remote buyers to explore properties virtually.')] },
  { slug: 'real_estate_analytics', name: 'Real Estate Analytics', description: 'Analyze market trends, property valuations, and investment opportunities with data science.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Property Intelligence', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Automated valuation models estimate property values using comparable sales.', 'Market analysis identifies neighborhoods with growth potential.', 'Investment modeling projects returns for rental and development properties.'] }], quiz: [q('What is an automated valuation model?', ['Manual appraisal', 'Statistical model estimating property value from data', 'Government assessment', 'Insurance quote'], 1, 'AVMs use algorithms and comparable data to estimate property values automatically.')] },
  { slug: 'proptech_ai', name: 'PropTech AI', description: 'Apply machine learning to property search, tenant screening, and predictive maintenance.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI in Real Estate', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Recommendation engines match buyers with properties based on preferences.', 'Tenant screening uses ML to assess rental application risk.', 'Predictive maintenance schedules building repairs before failures occur.'] }], quiz: [q('How does AI improve property search?', ['Shows all properties', 'Matches buyer preferences with relevant property recommendations', 'Reduces listings', 'Increases prices'], 1, 'AI learns buyer preferences to surface properties most likely to match their needs and desires.')] },
  { slug: 'proptech_enterprise', name: 'PropTech Enterprise', description: 'Scale real estate platforms with transaction management, CRM, and multi-market operations.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Real Estate Platform Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Transaction management coordinates offers, inspections, and closings digitally.', 'CRM systems track client relationships and communication history.', 'Multi-market platforms support operations across different regions and property types.'] }], quiz: [q('What is digital transaction management in real estate?', ['Paper contracts only', 'Digital coordination of offers, inspections, and closings', 'Online marketing', 'Social media'], 1, 'Digital transaction management streamlines the closing process with electronic signatures and workflows.')] },
];
