import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Retail & E-Commerce',
  slug: 'retail-personalization',
  description: 'Build modern retail platforms with personalization, omnichannel, and inventory optimization.',
  orderIndex: 41,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'ecommerce_basics', name: 'E-Commerce Basics', description: 'Build online storefronts with product catalogs, shopping carts, and checkout systems.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Online Store Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Product catalogs manage SKUs, descriptions, pricing, and inventory levels.', 'Shopping carts handle session management and order assembly.', 'Checkout systems process payments and calculate shipping and taxes.'] }], quiz: [q('What is the primary function of an e-commerce product catalog?', ['Marketing only', 'Centralized management of product information and inventory', 'Social media', 'Email marketing'], 1, 'Product catalogs serve as the central source for all product data displayed to customers.')] },
  { slug: 'inventory_optimization', name: 'Inventory Optimization', description: 'Balance inventory levels across channels with demand sensing and replenishment automation.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Smart Inventory Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Demand sensing uses real-time sales data to predict inventory needs.', 'Safety stock calculations buffer against demand variability.', 'Automated replenishment triggers purchase orders when stock reaches thresholds.'] }], quiz: [q('What is demand sensing?', ['Manual forecasting', 'Using real-time data to predict short-term demand', ' historical analysis only', ' Supplier communication'], 1, 'Demand sensing analyzes current sales patterns to make accurate short-term demand predictions.')] },
  { slug: 'omnichannel', name: 'Omnichannel Retail', description: 'Unify online and offline shopping experiences with consistent inventory and customer data.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Unified Shopping Experience', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Buy online, pick up in store (BOPIS) bridges digital and physical shopping.', 'Endless aisle allows store associates to order out-of-stock items for customers.', 'Unified customer profiles track interactions across all channels.'] }], quiz: [q('What is BOPIS?', ['Online only shopping', 'Buy Online, Pick Up In Store', 'Bulk Order Processing System', 'Business Order Processing'], 1, 'BOPIS combines online ordering with in-store pickup for convenient customer experiences.')] },
  { slug: 'recommendation_engine', name: 'Recommendation Engine', description: 'Personalize product suggestions with collaborative filtering and deep learning models.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Personalized Product Discovery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Collaborative filtering suggests products based on similar customer behavior.', 'Content-based filtering recommends items similar to products viewed or purchased.', 'Deep learning models capture complex patterns in browsing and purchase history.'] }], quiz: [q('How does collaborative filtering work?', ['Based on product features only', 'Recommends products liked by similar customers', 'Random suggestions', 'Staff picks only'], 1, 'Collaborative filtering identifies customers with similar tastes and recommends products they enjoyed.')] },
  { slug: 'retail_ai', name: 'Retail AI', description: 'Apply machine learning to visual search, pricing optimization, and customer service automation.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Retail', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Visual search lets customers find products by uploading photos.', 'Dynamic pricing adjusts prices based on demand, competition, and inventory.', 'Chatbots handle customer inquiries and provide personalized assistance.'] }], quiz: [q('What is visual search in retail?', ['Text search only', 'Finding products by uploading images', 'Voice search', 'Barcode scanning only'], 1, 'Visual search uses computer vision to match uploaded photos with similar products in the catalog.')] },
  { slug: 'retail_enterprise', name: 'Retail Enterprise', description: 'Scale retail operations with multi-brand, international, and franchise management platforms.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Global Retail Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Multi-brand platforms manage separate product lines under one infrastructure.', 'International retail handles multi-currency, multi-language, and local regulations.', 'Franchise systems ensure brand consistency while allowing local customization.'] }], quiz: [q('What challenge does international retail technology solve?', ['Faster shipping only', 'Multi-currency, language, and regulatory compliance across markets', 'Better products', 'Lower prices'], 1, 'International platforms handle currency conversion, translations, and local compliance requirements.')] },
];
