import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Social Media & Communication',
  slug: 'social-media-scale',
  description: 'Build scalable social platforms with real-time messaging, content sharing, and community features.',
  orderIndex: 33,
  theme: 'CRYSTAL' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'social_platform', name: 'Social Platform Basics', description: 'Understand user-generated content, social graphs, and real-time feed architectures.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Social Platform Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Social graphs model relationships between users for connections and feeds.', 'User-generated content requires storage, moderation, and delivery at scale.', 'Real-time feeds push updates to followers instantly when content is posted.'] }], quiz: [q('What is a social graph?', ['User profile picture', 'Network of connections between users', 'Posting algorithm', 'Login system'], 1, 'Social graphs map relationships between users to power friend lists, feeds, and recommendations.')] },
  { slug: 'realtime_messaging', name: 'Real-Time Messaging', description: 'Build chat applications with WebSocket connections, message history, and presence indicators.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Instant Messaging Infrastructure', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['WebSocket connections provide bidirectional real-time communication.', 'Message persistence stores chat history for offline access and search.', 'Presence indicators show user online status and typing notifications.'] }], quiz: [q('Why use WebSocket instead of HTTP for chat?', ['Faster internet', 'Persistent bidirectional connection for real-time messaging', 'Simpler code', 'Better security'], 1, 'WebSockets maintain persistent connections for instant message delivery without repeated HTTP requests.')] },
  { slug: 'content_moderation', name: 'Content Moderation', description: 'Automate content review with AI detection, human moderation, and community flagging systems.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Safe Content Delivery', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Machine learning detects inappropriate images, text, and videos automatically.', 'Human reviewers handle edge cases and appeals for moderation decisions.', 'Community flagging empowers users to report harmful content for review.'] }], quiz: [q('What is the best approach for content moderation?', ['AI only', 'Combination of AI detection and human review', 'Community only', 'No moderation'], 1, 'Effective moderation combines automated detection with human judgment for accuracy and fairness.')] },
  { slug: 'feed_algorithm', name: 'Feed Algorithms', description: 'Design ranking algorithms that surface relevant content while maintaining engagement metrics.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Content Ranking Systems', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Engagement signals like likes, comments, and shares influence content ranking.', 'Recency weighting ensures fresh content appears in user feeds.', 'Personalization learns individual preferences to customize each user\'s feed.'] }], quiz: [q('What signal is most important for feed ranking?', ['Post length', 'User engagement signals', 'Time of day', 'Number of hashtags'], 1, 'Engagement metrics like clicks, likes, and comments indicate content quality and relevance.')] },
  { slug: 'social_ai', name: 'Social AI', description: 'Apply machine learning to recommendations, content understanding, and spam detection.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Social Features', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Recommendation engines suggest accounts and content based on user interests.', 'Natural language processing detects spam, harassment, and policy violations.', 'Computer vision analyzes uploaded images for content understanding and moderation.'] }], quiz: [q('How do platforms recommend accounts to follow?', ['Random selection', 'Based on user interests and social connections', 'Paid promotion only', 'Geographic proximity only'], 1, 'Recommendation systems analyze user behavior and connections to suggest relevant accounts and content.')] },
  { slug: 'social_enterprise', name: 'Social Enterprise', description: 'Scale social platforms with viral growth patterns, monetization, and global infrastructure.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Scaling Social Platforms', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Viral loops encourage users to invite others through sharing and referrals.', 'Advertising platforms generate revenue from targeted user engagement.', 'Global CDN ensures fast content delivery for users worldwide.'] }], quiz: [q('What drives viral growth on social platforms?', ['Paid advertising', 'User invitations and content sharing', 'Better technology', 'Lower prices'], 1, 'Viral growth occurs when users naturally share content and invite others to join the platform.')] },
];
