import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Sustainability & Clean Tech',
  slug: 'sustainability-tech',
  description: 'Build sustainable technology solutions with carbon tracking, renewable energy, and green computing.',
  orderIndex: 47,
  theme: 'HARBOR' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'carbon_tracking', name: 'Carbon Tracking', description: 'Measure, report, and reduce carbon emissions with cloud-based sustainability tools.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Carbon Footprint Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS Customer Carbon Footprint Tool estimates emissions from AWS usage.', 'Scope 1, 2, and 3 emissions categorize different sources of carbon output.', 'Carbon reduction targets align with science-based goals and net-zero commitments.'] }], quiz: [q('What does the AWS Customer Carbon Footprint Tool measure?', ['Hardware defects', 'Estimated carbon emissions from AWS service usage', 'Network latency', 'Software bugs'], 1, 'The tool calculates estimated emissions associated with your AWS cloud workload consumption.')] },
  { slug: 'green_computing', name: 'Green Computing', description: 'Optimize cloud workloads for energy efficiency with right-sizing and sustainable architectures.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Energy-Efficient Cloud', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Right-sizing eliminates over-provisioned resources consuming unnecessary energy.', 'Spot Instances use otherwise idle capacity for cost and carbon savings.', 'Graviton processors provide better performance per watt than traditional processors.'] }], quiz: [q('How do Graviton processors improve sustainability?', ['Cheaper price', 'Better performance per watt reduces energy consumption', 'Faster speed only', 'Lower memory'], 1, 'ARM-based Graviton processors deliver more compute per watt of energy consumed.')] },
  { slug: 'renewable_energy', name: 'Renewable Energy', description: 'Support renewable energy procurement and understand AWS sustainability commitments.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Clean Energy Transition', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['AWS has committed to powering operations with 100% renewable energy.', 'Power Purchase Agreements support new renewable energy projects.', 'Carbon offset programs compensate for emissions that cannot be eliminated.'] }], quiz: [q('What is AWS\'s renewable energy commitment?', ['50% by 2025', '100% renewable energy', 'No commitment', '75% by 2030'], 1, 'AWS is on a path to power operations with 100% renewable energy by 2025.')] },
  { slug: 'circular_economy', name: 'Circular Economy', description: 'Extend hardware lifecycle, reduce e-waste, and implement circular economy principles in tech.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Sustainable Hardware Practices', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Hardware refurbishment extends equipment life and reduces manufacturing demand.', 'Responsible recycling ensures proper disposal of electronic components.', 'Cloud adoption reduces on-premises hardware requirements.'] }], quiz: [q('How does cloud computing support circular economy?', ['More hardware needed', 'Reduces on-premises hardware through shared infrastructure', 'Increases e-waste', 'No impact'], 1, 'Cloud computing consolidates workloads on shared infrastructure, reducing overall hardware requirements.')] },
  { slug: 'sustainability_ai', name: 'Sustainability AI', description: 'Apply machine learning to climate modeling, energy optimization, and environmental monitoring.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI for Sustainability', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Climate models predict environmental changes using machine learning.', 'Building energy optimization reduces consumption through intelligent controls.', 'Environmental monitoring tracks deforestation, pollution, and biodiversity.'] }], quiz: [q('How does AI help building sustainability?', ['Increases energy use', 'Optimizes HVAC and lighting for reduced energy consumption', 'No impact', 'Faster internet'], 1, 'AI optimizes building systems to reduce energy consumption while maintaining occupant comfort.')] },
  { slug: 'sustainability_enterprise', name: 'Sustainability Enterprise', description: 'Integrate sustainability reporting, ESG compliance, and green software practices across organizations.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Enterprise Sustainability', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['ESG reporting frameworks standardize sustainability disclosures.', 'Green software practices optimize code efficiency and reduce compute needs.', 'Sustainable procurement includes environmental criteria in vendor selection.'] }], quiz: [q('What is green software development?', ['Using green computers', 'Writing efficient code that minimizes computational resources', 'Only open source', 'Mobile-only development'], 1, 'Green software development focuses on creating efficient applications that use fewer computational resources.')] },
];
