import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'Travel & Transportation',
  slug: 'travel-logistics',
  description: 'Build booking engines, logistics platforms, and connected transportation systems on AWS.',
  orderIndex: 39,
  theme: 'FORGE' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'booking_systems', name: 'Booking Systems', description: 'Build scalable reservation engines for hotels, flights, and travel experiences.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'Reservation Platform Architecture', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Inventory management tracks availability across rooms, seats, and experiences.', 'Dynamic pricing adjusts rates based on demand, seasonality, and competition.', 'Payment processing handles multi-currency transactions and refunds.'] }], quiz: [q('What is dynamic pricing in travel?', ['Fixed prices', 'Adjusting rates based on demand and market conditions', 'Discount only', 'Price freezing'], 1, 'Dynamic pricing optimizes revenue by adjusting prices based on real-time demand and supply.')] },
  { slug: 'fleet_tracking', name: 'Fleet Tracking', description: 'Monitor vehicle fleets with GPS, route optimization, and driver behavior analytics.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Fleet Management Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['GPS tracking provides real-time vehicle location and historical routes.', 'Route optimization reduces fuel costs and delivery times.', 'Driver scoring identifies risky behaviors for safety improvement programs.'] }], quiz: [q('How does fleet tracking reduce costs?', ['Increases speed', 'Optimizes routes and monitors driver behavior', 'Reduces vehicles', 'Eliminates maintenance'], 1, 'Route optimization and driver behavior improvement reduce fuel consumption and maintenance costs.')] },
  { slug: 'logistics_optimization', name: 'Logistics Optimization', description: 'Optimize supply chain operations with demand forecasting and warehouse automation.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Supply Chain Intelligence', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Demand forecasting predicts inventory requirements for distribution centers.', 'Warehouse automation uses robotics and ML for picking and packing efficiency.', 'Last-mile delivery optimization reduces shipping costs and delivery times.'] }], quiz: [q('What is last-mile delivery optimization?', ['First delivery only', 'Reducing cost and time for final delivery to customers', 'Warehouse storage', 'Bulk shipping'], 1, 'Last-mile optimization focuses on the most expensive part of delivery - getting products to customers.')] },
  { slug: 'travel_personalization', name: 'Travel Personalization', description: 'Create personalized travel experiences with recommendation engines and preference learning.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Customized Travel Experiences', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Recommendation engines suggest destinations and activities based on traveler preferences.', 'Context-aware offers adjust recommendations based on location, time, and weather.', 'Loyalty programs track preferences and reward frequent travelers.'] }], quiz: [q('How do travel platforms personalize recommendations?', ['Random suggestions', 'Analyze traveler preferences and behavior patterns', 'Show cheapest options only', 'Manual curation'], 1, 'Machine learning analyzes booking history and preferences to suggest relevant travel options.')] },
  { slug: 'transportation_ai', name: 'Transportation AI', description: 'Apply machine learning to route planning, demand prediction, and autonomous vehicle systems.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'AI-Powered Transportation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Predictive models forecast demand for ride-sharing and delivery services.', 'Computer vision enables autonomous vehicle navigation and safety systems.', 'Natural language processing powers voice assistants for travel booking.'] }], quiz: [q('What is the primary AI application in ride-sharing?', ['Marketing only', 'Predicting demand and matching drivers with riders efficiently', 'Vehicle design', 'Road construction'], 1, 'AI optimizes driver positioning and rider matching to reduce wait times and increase efficiency.')] },
  { slug: 'transport_enterprise', name: 'Transportation Enterprise', description: 'Scale transportation platforms with multi-modal integration, compliance, and global operations.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Global Transportation Platform', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Multi-modal integration combines flights, hotels, cars, and activities.', 'Regulatory compliance manages permits, insurance, and safety requirements.', 'Global operations support multiple languages, currencies, and local regulations.'] }], quiz: [q('What is multi-modal transportation integration?', ['Single vehicle type', 'Combining multiple transportation modes in one platform', 'Only flights', 'Local delivery only'], 1, 'Multi-modal platforms offer comprehensive travel planning across flights, ground transport, and accommodations.')] },
];
