import type { CurriculumSlide, CurriculumQuiz, CurriculumModule } from './aws-roadmap';
export type { CurriculumSlide, CurriculumQuiz, CurriculumModule };

export const TOPIC = {
  name: 'VMware Cloud on AWS',
  slug: 'vmware-cloud-aws',
  description: 'Run VMware workloads natively on AWS infrastructure for hybrid cloud flexibility.',
  orderIndex: 25,
  theme: 'TECH' as const,
};

const LETTERS = ['A', 'B', 'C', 'D'] as const;
function q(question: string, options: string[], answerIndex: number, explanation: string): CurriculumQuiz {
  return { question, optionA: options[0], optionB: options[1], optionC: options[2], optionD: options[3], correctAnswer: LETTERS[answerIndex], explanation };
}

export const CURRICULUM_MODULES: CurriculumModule[] = [
  { slug: 'vmware_basics', name: 'VMware Cloud Basics', description: 'Understand vSphere, vSAN, NSX-T, and VMware Cloud on AWS architecture.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 0, slides: [{ title: 'VMware on AWS Foundation', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['VMware Cloud on AWS runs vSphere clusters on bare-metal AWS infrastructure.', 'vSAN provides hyper-converged storage for VM data persistence.', 'NSX-T delivers software-defined networking and micro-segmentation.'] }], quiz: [q('What storage technology does VMware Cloud on AWS use?', ['EBS', 'vSAN', 'S3', 'EFS'], 1, 'vSAN aggregates local NVMe storage into a distributed datastore for VM storage.')] },
  { slug: 'vmware_networking', name: 'VMware Networking', description: 'Configure NSX-T networking, VPN connectivity, and hybrid cloud network integration.', level: 'BEGINNER', tier: 'Fundamentals', xpPoints: 50, orderIndex: 1, slides: [{ title: 'Software-Defined Networking', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['NSX-T provides overlay networking between VMware Cloud and on-premises environments.', 'AWS Direct Connect or VPN extends corporate networks to VMware Cloud on AWS.', 'Distributed firewall rules secure traffic between VMs without physical appliances.'] }], quiz: [q('How do you connect on-premises networks to VMware Cloud on AWS?', ['Only VPN', 'Direct Connect or VPN', 'Public internet only', 'VPC peering'], 1, 'Direct Connect provides dedicated, low-latency connectivity while VPN offers encrypted tunnel connections.')] },
  { slug: 'vmware_migration', name: 'VMware Migration', description: 'Migrate workloads with HCX for bulk transfer, live migration, and zero-downtime moves.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 2, slides: [{ title: 'Workload Migration Tools', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['HCX enables bulk migration of thousands of VMs with minimal downtime.', 'vMotion live migrates running VMs between on-premises and cloud without interruption.', 'Replication-based migration provides asynchronous data transfer for large datasets.'] }], quiz: [q('What does HCX stand for?', ['Hybrid Cloud Extension', 'High Capacity Transfer', 'Hardware Configuration Explorer', 'Host Cluster Manager'], 0, 'HCX provides hybrid cloud capabilities for workload mobility across environments.')] },
  { slug: 'vmware_operations', name: 'VMware Operations', description: 'Monitor, scale, and manage VMware Cloud on AWS with automated operations and policies.', level: 'INTERMEDIATE', tier: 'Associate', xpPoints: 75, orderIndex: 3, slides: [{ title: 'Operational Management', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Auto-scaling adds or removes ESXi hosts based on cluster resource utilization.', 'DRS balances VM workloads across hosts for optimal performance.', 'Policies define resource allocation, storage tiers, and backup schedules.'] }], quiz: [q('What does DRS do in VMware Cloud on AWS?', ['Distributes resources', 'Balances VM workloads across hosts for optimal performance', 'Encrypts data', 'Monitors costs'], 1, 'DRS automatically migrates VMs between hosts to balance resource usage and maintain performance.')] },
  { slug: 'vmware_security', name: 'VMware Security', description: 'Implement micro-segmentation, identity management, and compliance for VMware workloads.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 4, slides: [{ title: 'Zero-Trust Security Model', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Micro-segmentation isolates workloads with fine-grained firewall policies.', 'Active Directory integration provides centralized identity and access management.', 'Compliance frameworks enforce security baselines across all virtual machines.'] }], quiz: [q('What is micro-segmentation?', ['Network segmentation at the VM level', 'Physical network isolation', 'VLAN configuration', 'Subnet planning'], 0, 'Micro-segmentation applies security policies at the individual VM or application level.')] },
  { slug: 'vmware_disaster_recovery', name: 'VMware Disaster Recovery', description: 'Protect VMware workloads with Site Recovery for automated failover and failback.', level: 'ADVANCED', tier: 'Professional', xpPoints: 100, orderIndex: 5, slides: [{ title: 'Business Continuity Planning', layoutType: 'TEXT_ONLY', imageUrl: null, bullets: ['Site Recovery provides automated disaster recovery between VMware Cloud regions.', 'Recovery plans define failover sequences, dependencies, and testing schedules.', 'Failback restores workloads to primary site after disaster recovery activation.'] }], quiz: [q('What is the purpose of VMware Site Recovery?', ['Backup files', 'Automated disaster recovery with failover and failback', 'Performance monitoring', 'Cost optimization'], 1, 'Site Recovery automates DR processes to minimize downtime and data loss during outages.')] },
];
